### ISSUE TITLE
[2-3] 코딩배우기 페이지 구조화

### ISSUE THREAD

**Issue by PACMAN-X** [ProjectInTheClass/CodersHighOffice#101]
- [x]  코딩배우기 페이지
- [ ]  코딩배우기 레이아웃 구성 확정 후 디자인 요청( to 민기 )

**Comment by lingostar** [comment]
이건 지난번에 만든 리플렛과 함께 

이번 부산 교육 리플릿 작업을 다시 하면서 웹 버전을 정리합시다.
