### ISSUE TITLE
[까페현대코딩] 인공지능도 아이패드로

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#121]
**1차 피드백**
1차 편집이니 전체적으로 편집 호흡이 느슨한 부분은 이야기 하지 않고 내용적으로 큰 흐름만 잡아보겠습니다. 동어 반복은 당연히 커트해서 덜어내 주는 거 알죠?
디테일한 편집은 2차 편집에서 잡을께요.

-- 인트로 --
- [x] '오랫만에 녹화하니 카메라 세팅도 제대로 못함 ㅋ' 효과자막 넣어주세요
- [x] '10만명의' 멘트는 좀 지워주세요 ㅋ
- [x] 'AI 교사 5천명 양성' 효과자막과 기사 캡처 http://www.edupress.kr/news/articleView.html?idxno=4452
- [x] '3일만에 고등학생이~~~' 이 부분 오디오 겹쳐요.

-- AI for Oceans --
- [x] 진입하는 부분 너무 자세히 follow-up하지 않아도 됩니다
- [x] 03:00 학습을 시작합니다 라고 하고 나서 바로 "해양 쓰레기~ " 로 커트. "AI 머신이 있죠?" 후 바로 "물고기인지 아닌지"로 커트
- [x] 물고기 학습 시키는 거 조금만 넣고, 해양오염과 관련한 정보 나오는 부분도 커트해 버리세요.
- [x] 2페이지 종료후에는 "Train More에 들어가서 좀 더 학습을 시킬 수도 있습니다" 부분이 중요한 부분임. 나머지는 덜어내도 됨.
- [x] 3페이지는 우리의 현재 모델로는 문어나 거북이를 인식할 수 없어서 해양 생물들이 걸러내 지고 있다는 것을 발견하는 페이지예요. 제가 멘트를 두번 땄으니 멘트 찾아서 넣어주세요. 화면이랑 멘트랑 분리해서 편집해야 할지도. 
- [x] 4페이지에서 이제 저런 문어나 거북이 해파리들도 살려내도록 학습을 시키는 겁니다. 
- [x] 해양 오염 상식들은 가능한한 다 덜어내 주세요.
- [x] 4페이지의 마지막은 "우리의 모델이 부족하네요. 더 많은 데이터로 학습을 시켜야 겠습니다" 로 끝나야 해요. 멘트가 없으면 자막으로라도.
- [x] 6페이지의 사각형 물고기는 아주 짧게 할 수 없으면 걷어내 버려도 됩니다.
- [x] 8 페이지가 핵심인데, 행복한 물고기나 가장 빠른 물고기.. 멘트는 메뉴가 보일 때 나와야 하고, 메뉴 화면이 좀 더 길었으면 좋겠어요. 확대나 사각형으로 강조해 줘도 좋을 듯.
- [x] 모두가 자기 분야에서 필요한 모델 학습은 스스로 시켜야 한다는 멘트는 효과자막. 
- [x] 편향된 데이터로 학습시키면 결과도 편향되어 나온다 멘트 효과자막

-- CreateML 파트 --
- [x] "머신러닝 학습 툴이 참 많죠" 부터 "가장 쓸모있는 모델을" 앞 까지 덜어내 주세요. "가장" 도 없애면 좋긴한데. 
- [x] 오디오가 갑자기 이상해요. 화면캡처에 있는 오디오를 쓰세요.
- [x] Train을 누르기 두려운 데요 이후 부분 삭제

-- 플레이그라운드 북 파트 --
- [x] 효과자막으로 "바이트대디의 수업을 들은 대학생이 만든 플레이그라운드 북" "코더스하이 콘텐츠"
- [x] YOLO 부분은 어차피 잘 인식 못하는 부분이니 확 덜어냅시다.
- [x] YOLO 부분에선 효과자막으로 "YOLO는 메모리 소모량이 많아서 플레이그라운드에선 잘 안될 수가 있어요."
- [ ] 현장감을 위해 내가 인형을 찍는 영상도 가끔씩 넣어주세요.
- [x] 학생들의 학습 데이터와 모델 자료화면 넣어줄께요.
-- 아웃트로 --
- [x] 이미지 추가할께요. 넣어주세요.

**2차 피드백**
- [x] code.org 에서 AI for Ocean 으로 진입하는 과정 좀 더 줄여주세요. 장면들을 컷 해도 돼요
- [x] Fish , Not Fish 누르는 장면은 아이폰 카메라 촬영 샷이 조금이라도 들어가면 좋겠어요. 첫 학습은 아이폰 캠으로 하고 학습결과 확인부터 아이패드 레코딩을 쓰는 건 어떨까요?
- [x] 03:17 ~ 03:20 덜어내 주세요
- [x]  "머신러닝 학습 툴이 참 많죠" 부터 "가장 쓸모있는 모델을" 앞 까지 덜어내 달라고 한 게 적용이 안되었어요. 그 이름들을 이야기 할 필요가 없을 것 같아요
- [x] 플레이그라운드 작업할 때는 카메라 샷도 적절히 섞어주세요
- [x] 학생들의 결과물은 엄청 중요하니 확대해서 한 번 천천히 훑어주세요. 내 얼굴보다 그 결과 페이지가 더 중요해요. 우리 영상의 하일라이트~! 시청자 중 선생님들은 그 결과에 제일 관심이 많을 꺼예요. "머신러닝에 대해 자신감을..." 멘트 전까지는 결과물의 시간. 
- [x] 회 사진과 돼지국밥 3 그릇 사진 부탁
- [x] 제목을 정해서 커버 아트 만듭시다. 제목에는 "아이패드" "인공지능" 이 들어가야 하고 유튜브 제목에는 "스위프트 플레이그라운드" 와 "Code.org"가 함께 들어가면 좋아요.

**Comment by aawlgus96** [comment]
nas에 업데이트해놨습니다~! 길이는 14분 30초정도 되네요

**Comment by lingostar** [comment]
@aawlgus96 수고 많았어요. 영상 잘 나왔네요. 아들이 옆에서 많이 웃었음. 2차 피드백 줬으니, 수정바랍니다.
