### ISSUE TITLE
온라인스쿨 iOS 앱 개발자 과정 입과 테스트 만들기

### ISSUE THREAD

**Issue by PACMAN-X** [ProjectInTheClass/CodersHighOffice#155]

**Comment by lingostar** [comment]
12주 과정으로 다시 리디자인

**Comment by lingostar** [comment]
@jin0yoon 님, 우리 게더의 학교 밖 학습공간을 마치고 입과하려는 사람들을 위한 자가점검 같은 테스트는 있어야 할 듯요. 

나중에 입과 대기생이 많아지면 통과를 해야 입과할 수 있도록 하는 것도 좋을 듯 해요.
