### ISSUE TITLE
코더스하이스쿨 온라인 페이지 만들기

### ISSUE THREAD

**Issue by PACMAN-X** [ProjectInTheClass/CodersHighOffice#156]
- 전체 과정을 총 망라하는 디자인

**Comment by lingostar** [comment]
온라인 스쿨에는  아래와 같은 상품이 있습니다.
이 상품들에 대한 포털 역할을 하는 페이지가 필요합니다.

- [ ] iOS 앱 개발자 과정 - 웹 페이지 , 스마트스토어 , 비대면 바우처
- [ ] 프로토타이퍼 과정 - 웹 페이지 , 스마트스토어 , 비대면 바우처
- [ ] Swift PT -  스마트스토어
- [ ] 온라인 핫데스크 -  스마트스토어
