### ISSUE TITLE
[드림인] 문제 정리

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#174]
수요일에 드림플러스 최종 점검 미팅을 합니다. 그 전에 문제 수를 조정해 놔야 해요.

문제 난이도
하 - 10
중 - 10
상 - 10

문제 순서는 정해지고 보기만 섞는 형태.

40분 30문항

같은 것을 고르는 것과 다른 것을 고르는 경우를 강조

- [x] 현재 문제 난이도 확인 및 저에게 공유
- [x] 문제 난이도 조정 계획 공유 후 조정
- [x] 문제 문항 갯수 조정 후 시간 조정/ 클래스 복제

**Comment by PACMAN-X** [comment]
| 난이도 | 배점 | 갯수 | 점수 | 유형
-- | -- | -- | -- | -- | --
  |   |   | 40 | 100 |  
유형 1 상 | 상 | 5 | 2 | 10 | 순서도
유형 1 중 | 중 | 3 | 2 | 6
유형 1 하 | 하 | 2 | 2 | 4
유형 2 | 중 | 3 | 3 | 9 | 도형 완성하기
유형 3 | 하 | 2 | 6 | 12 | 순서도에 맞는 도형 고르기
유형 4 | 하 | 2 | 6 | 12 | 도형 비례식
유형 5 | 최하 | 1.5 | 6 | 9 | 다른 도형 고르기
유형 6 | 최하 | 1.5 | 6 | 9 | 같은 도형 찾기
유형 7 | 중 | 3 | 3 | 9 | 거짓말 추리
유형 8 | 상 | 5 | 2 | 10 | 순서 위치 추리
유형 9 | 상 | 5 | 2 | 10 | 복합 추리

**Comment by PACMAN-X** [comment]
현재는 위와 같은 형태로 구성 되어 있습니다.

**Comment by PACMAN-X** [comment]
문제 난이도 조정

**Comment by lingostar** [comment]
@PACMAN-X 그럼 순서는 유형 1 하 - 유형 4 하 - 유형 5 하 - 유형 6 하 - 유형 1 중 - 유형 2 중 - 유형 3 중 - ....
순서로 가는 건가요?
