### ISSUE TITLE
041_Unit4_4_Scroll Views

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#179]
**4차 피드백 by 링고**
- [x] 전체적으로 프로젝트내의 화면이 오른쪽으로 치우친 느낌이예요. 추출한 영상을 보면 오른쪽 여백이 왼쪽에 비해 현저하게 적고, PIP가 잘리는 느낌까지 있어요.
- [x] 03:46 연결부분 오디오가 좀 튀어요. 충분히 편집했을텐데...아마 어쩔 수 없었겠죠.
- [x] 04:01 "레슨에서는" 에서 "레"가 없음.
- [x] 06:17 따로 녹화한 거 좋아요 👍🏻. 녹화한 화면이 지금 나오는 타이밍에 나오고, 정지화면으로 3초만 더 있다가 플레이하면 좋을 듯.
- [x] 10:44 비디오가 잠깐 멈춘거 같은데, 이런 방식을 사용하지 않았어서 좀 어색해요. 동영상 위에 효과자막을 넣을 수 없나요?
- [x] 19:20 목소리 연결 좀 더 자연스럽게 안될까요?
- [x] 24:28 유튜브 영상 연결하는 건 좋은데, 너무 짧게 지나가니까 좀 늘려주세요. 그리고 "스위프트하이 채널 검색" 이라는 효과자막도 넣어주세요.
- [x] 25:54 효과자막이 떨리는게 주목을 끌기 위한 것 같은데... 좀 움직임이 어색해요. 안 어색한 움직임을 만들거나 움직이지 않는 걸로.

**3차 피드백 by 민지**
- [x] 02:29 책에 맞게 소문자 f가 더 낫지 않을까 싶네요!
- [x] 10:39 동일한 크기가 된 모습이 너무 잠깐 나와서 그 모습을 조금 더 길게 보여주면 좋을 것 같아요. 동일한 크기가 됩니다 이 멘트할 때 동일해진 모습을 보여주던가 아니면 좋아요하고 조금 시간을 두던가 하는 방식으로 조정해주세요!
- [x] 16:02 확대 화면 넣어주세요.
- [x] 16:18 15:09의 8 8 이 부분 화면 잘라서 넣어주세요.
- [x] 16:29 제가 드린 자료화면 넣어주세요.
- [x] 24:20 Next Step 이 뭐지 하는 의문 가질 수 있으니까 https://youtu.be/DXGeNEItpiY?t=76 여기 유투브 썸네일 캡쳐해서 Next Step이 궁금하다면? 뭐 이런식으로 넣는게 어떨까 싶네요.(저 유투브 영상에 해당 내용이 나와서!) (아니면 아에 빼던가?) - 일단 넣고 나중에 대표님 피드백에서 확인 받으면 될 듯!
- [x] 24:48 책 화면 넣어주세요.
- [x] 30:32 22:06의 자료 화면 한번 더 넣어주세요.
- [x] 35:27 말풍선 자막 넣어주세요.
- [x] 36:06 짤이 너무 길게 나와서 좀만 짧게 해주세요.

**2차 편집 계획 by zio**
- 0:00 "중요한 키워드' 효과자막
- 0:00 "중요한 내용' 그래픽 - zio 제작
- [x] 01:14 'bounds', 'frame' 강조 자막
- [x] 02:22 'frame', 'contentSize' 강조 자막
- [x] 02:55 scrollView frame 표시해주기
- [x] 08:26 stack view 강조 자막
- [x] 09:30 더미 사진
- [x] 10:26 안보이지만 있는거 표시
- [x] 10:50 '사이즈는 ~ 결정됨' 자막
- [x] 11:18 label, switch 이미지
- [x] 12:46 label 그림에 표시해주기 손모양으로
- [x] 13:00 책장 휘리릭 넘기는 열공하는 짤
- [x] 13:10 text field 그림에 표시해주기
- [x] 15:02 화면에 leading, trailing 표시
- [x] 17:08 추가되는거 강조
- [x] 18:04 스크롤뷰 강조
- [x] 18:16 나쁜짓
- [x] 18:39 자동으로 넣는거 - 왜 너맘대로 해? 짤
- [x] 19:25 900 상수값 -> 0 효과자막
- [x] 20:22 오디오 겹침
- [x] 20:42 당연하지 짤
- [x] 20:54 notification center 효과 자막
- [x] 22:01 EdgeInset 강조
- [x] 28:48 이런 세심함 까지~ 효과자막
- [x] 31:15 'top과 ~ 여백을 편하게줄수있음' 강조 자막
- [x] 31:42 rgrg 짤
- [x] 32:00 스크롤뷰 일가 짤
- [x] 32:44 해보세요 효과자막
- [x] 33:49 적당한 짤 넣기
- [x] 34:31 직접해보시기바랍니다 효과자막
- [x] 34:49 당황 짤
- [x] 35:16 허헣/머쓱타드 짤
- [x] 35:51 게임 짤 넣기
- [x] 36:35 가속 감속 강조 자막
- [x] 37:08 자신감 뿜뿜 짤

**2차 피드백 by Lingo**
- [x] 00:58 '스크롤뷰의 향연' 짤 
- [x] 02:57 스크롤 프레임안에서 스크롤 콘텐츠가 움직이는 거 표현
- [x] 09:23 자동차 더미 사진

**1차 피드백 by Lingo**
- [x] 04:38 스크롤링 폼 이라는 말의 시작 부분이 오디오가 이상해요
- [x] 05:04  '싱글뷰' 도 위와 같아요. 커트점 잡는 부분이 오디오 시작부분을 잡아먹는 방식인듯. 앞부분에 1분 이내에 이런 부분이 또 있었거든요.
- [x] 06:20 효과자막으로 "메뉴가 안 보여요~~!!" 라고 넣어주세요. 
- [x] 06:25 "그래서 제가 따로 녹화했습니다 ㅜㅜ" 효과자막 . 그리고 영우씨가 Xcode에서 저 부분 녹화할 수 있으면 녹화해서 우리 보통 메뉴 확대해서 보여주는 방식으로 보여주세요. 모르겠으면 영상 요청하세요. 녹화가 어려우면 책의 스크린 샷 그냥 넣어줘도 될 듯 하네요.
- [x] 10:40 "pin 메뉴 또 안 보여요~~" 효과자막.녹화가 어려우면  책의 스크린 샷 그냥 넣어줘도 될 듯 하네요.
- [x] 10:43 의미 없는 컷이 끼어있는 것 같네요
- [x] 10:19 Intrinsic Size 효과자막

------------------------------------------------------------------------------
- [x] 15:25 *이걸 넣을지 말지 결정.-> 여기부터 덜어냅시다
- [x] 17:04 이 때는 화면이 아예 안 나오네.. 이건 가능하면 뺍시다. 위쪽 이슈랑 같이
- [x] 17:35 이런 헤매는 건 뺍시다. 돈 내고 보는 사람들인데...
- [x] 18:30 세 단계 위의 뷰와 컨스레인트를 먹인다는 얘기 뒤에도 했던 거 같은데, 앞쪽을 아예 뺍시다. 
- [x] 실패를 보여주는 이유는, Xcode 버전에 따라 사용자들도 동일하게 경험할 가능성이 있는 것들만 남깁시다. 
- [x] 특히 20:50 처럼 "이제 됐... 아이씨"는 혼잣말이라서 반드시 잘라줘야 해요. 웃기게 살려내지 못하면 시청자가 기분 나쁠 수 있어요. 
- [x] 33:20 여기까지 덜어냅니다. "이제 다시 정신차리네요" 멘트는 앞쪽과 연관성이 없으면 덜어내야 할 멘트.
-------------------------------------------------------------------------------------------
- [x] 36:40 '도큐멘트 아웃라인으로'라는 말이 좀 끊어지는 느낌이예요
- [x] 37:19 스크롤 안되는거 중간에 엉뚱한 거 만지는 건 덜어내주세요
- [x] 37:20 어색한 침묵 덜어내 주세요
- [x] 39:20 까지 덜어내 주세요.
- [x] '새 버전의 Xcode 와' 부분 오디오 왜 튀죠?
- [x] 38:40 부분의 '자동으로 나쁜짓을~~~' 부분만 잘 살려주면 됩니다. 이걸 위해 필요한 앞 쪽을 살리는 방식으로 편집
- [x] 뭔가 오랜 기간의 삽질로 고생한 건 그냥 나의 책임인 걸로. 시청자들이 여기에 공감하기 어렵고 공감할 필요도 없어요.
- [x] 40:40 속도감 있게 말하는 건 좋은데, 멘트가 먹히면 안돼요.
- [x] 42:42 '달라요' 걷어내 주세요
- [x] 47:18 'Best Practice' 효과 자막
- [x] 47:20 커트 점에서 사운드가 튀어요
- [x] 55:55 '더이상 축소가 되지 않아야 하잖아요' 오디오 좀 이상해요

끝~!

- [x] 녹화 당시 상황 전달 : 2개의 녹화 파일이 있어요. 1번의 마지막 부분에, 오토레이아웃 문제가 해결이 안되어서 하다가 끊고 다시 합니다. ScrollForm 예제를 시작하는 시점에 뒷 부분 영상을 확인 한 뒤, 실습 부분은 뒷 부분 영상을 활용해 주세요.

> Cam
- 하이어~ 오늘 배울 건 스크롤 뷰. 아이폰 화면은 작고, 우리가 봐야 할 콘텐츠는 크기 때문에 많이 사용. 
- 이번에 바운즈 프레임 개념 나오나?
- HIG 에도 스크롤 뷰

**Comment by geniusnam** [comment]
55:55 '더이상 축소가 되지 않아야 하잖아요' 오디오 좀 이상해요

**Comment by geniusnam** [comment]
'새 버전의 Xcode 와' 부분 오디오 왜 튀죠?
-> 링고님이 새 버전의 Xcodeeeeeeeee와  이렇게 해서 음맞추기가 어렵네요...

**Comment by geniusnam** [comment]
36:40 '도큐멘트 아웃라인으로'라는 말이 좀 끊어지는 느낌이예요
-> 원본영상에서 링고님이 말을 다시하시면서 끊기게 된것 같습니다.

**Comment by geniusnam** [comment]
위의 거는 무시해주세요 ㅠㅠ

**Comment by lingostar** [comment]
@manju-minji 이 영상도 편집해 주세요

**Comment by lingostar** [comment]
@zihos 님이 이 영상의 2차편집 ~ 완성까지를 맡아주세요.
먼저 내용파악을 하면서 효과자막과 그래픽 계획 그리고 짤방 계획을 작성해 주세요.
