### ISSUE TITLE
043_Unit4_6_Intermediate Table Views

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#182]
**4차 피드백 by Lingo**
- 자를 수 있는 시각 18:24 , 44분 즈음 , 61분? 즈음(CompressionResistence),  
- [x] 08:25 'Intrinsic Size : 내재적 크기' 효과자막
- [x] 18:50 즈음과 19:00 즈음에 슬랙 메세지 알람소리가 나는데.. '쓰앵님 알람 끄고 녹화하셔야지요' 정도 효과자막
- [x] 21:50 '쓰앰, 알람~!' 약간 짜증느낌 효과자막
- [x] 29:30 Sell -> Cell . 왜 이래? 선수끼리!
- [x] 31:07 HIG 를 좀 자세히 보시면~ 부터는 사족인듯. 이 앞 부분도 "이 분이 잘 못 알고 있다"는 말을 너무 많이 했네. 작은 잘못에 너무 큰 벌을 내리는 것 같으니, HIG를 잘 못 알고 있다는 얘기는 가능한 줄여봅시다. 어색하지 않은 한에서.
- [x] 42:50 그림 그린 곳에 🤩 이모지 넣어주세요 ㅋ

**3차 피드백 by 민지**
- [x] 지난번 48:57 피드백 드린게 48:51쯤에서 축소되는 화면을 saveBu 치고 나서 축소해달라는 말인데 48:51쯤에서 한번 축소되고 또 그 뒤에 saveBu 후에 전체 화면이 축소되는데 일부러 이런 효과를 넣으신건가요?

---
- [x] 1:04:07 라인프렌즈쪽에 나오는 자막들을 말 끝날 때 말고 말 하는 동안 해당 내용에 대한 자막 띄워주는게 어떨까요.
        -> 말씀하신대로 했는데 다시 보니 수정 전후 모두 좀 단조롭다는 느낌이 들어서 설명에 맞는 그림을 띄워보았습니다! 확인 부탁드립니다
---
**2차 피드백 by 민지**

- [x] 08:54 뭔가 갑자기 넘어가는 느낌이 드는데 한번 확인해주시고 좀 더 자연스럽게 넘어갈 수 있도록 해주세요.
- [x] 12:23 ~ 12:26 검은 화면만 나옴.
- [x] 12:38 누를 때 까지 확대 말풍선 둡시다.
- [x] 13:48 2배속 자막이 뭔가 앞으로 좀 밀린거 같에요 진짜 2배속 장면보다 더 빨리 등장하고 빨리 사라지는 것 같네요.
- [x] 17:18 실행할 때 stop하는 장면 같은 건 덜어내는 게 낫지 않을까요?
- [x] 18:23 여기도 갑자기 넘어가는 느낌 듦.
- [x] 24:34 지난번 24:32 피드백 드린 것과 같은데, 파컷 열어서 확인 해보니까 처음에는 파컷에서도 움직이더라고요. 몇 번 반복해서 보니까 안 움직이던데 추출 하시기 전에 한번 어떤지 확인하고 추출해주시고 알려주세요~
- [x] 26:31 여기도 말 짤림
- [x] 27:49 똑똑하네 라는 자막이 묻히는 느낌.
- [x] 48:57 화면 축소 여기쯤에서 해주세요
- [x] 56:18 연결 더 자연스럽게
- [x] 1:00:31 문제 해결 부분까지 확대 화면으로 보여주세요.
- [x] 1:06:01 여기서 말하는 name이 바로 앞의 symbol이랑 같은 것 아닌가요? 같다면 손 가르키는거 위치랑 등장 타이밍을 좀 바꿔야 할 듯.

---

- [x] 13:12 이 짤은 무슨 의미인가요??
       -> "책이 자세히 안나와있어서 알려주기 위해서 제가 있는거죠" 라고 하는 내용이라서 알려주는 것이 감사하다는 의미로 넣었습니다..!
            의미가 잘 전달되지 않는 것 같아서 삭제했습니다
- [ ] 40:25 여기서 화면 축소 하도록 해주세요.
       -> 화면이 전환될 때 축소되게 하라는 말씀이신가요? 혹시 몰라서 아직 진행 안했습니다.
- [x] 이번에도 파컷에 배속 자막 포함 안됐고, 연지님이 만든 라이브러리에 포함 된 자막 보면 동일한 자막이 여러 복제본을 가지고 있는데(지금까지 복제본 생겨도 이렇게 많은 복제본 생긴 경우는 못 본 것 같네요) 혹시 자막 넣을 때 어떻게 하시나요? 확인해보시고 slack으로 답변 주세요.

**1차 피드백 by 민지**
- [x] 01:07 허들 화질도 그렇고 이미지도 뭔가 화면 쪽으로 기우는 것 같아서 https://www.flaticon.com/search?word=hurdle 여기서나 아니면 다른 곳에서 좀 더 깔끔하고 더 표현 잘 할 수 있는 이미지로 변경해주시면 좋을 것 같네요.
- [x] 01:17 허들 등장 타이밍이랑 사라지는 타이밍이 뭔가 어색한데 좀 더 깔끔하게 조정 가능할까요?
- [x] 02:30 ~ 관련 이미지 캡쳐해서 넣어주세요.
- [x] 03:14 여기만 설명하고 없애기 보다는 뒤에 작았잖아요 이 부분도 해당 이미지로 설명 추가해주세요.
- [x] 07:16 효과 자막을 바꾸던 글씨크기를 줄이던 해서 화면 밖으로 좀 덜 나가게 해주시고, 등장 타이밍을 말 시작할 때로 바꿔주세요.
- [x] 08:29 쎄게 -> 세게
- [x] 09:44 우리의 cell class 만들어야한다 이런 식으로 효과자막 추가
- [x] 10:54 컨텐츠가 커지는 게 잘 안보여서, 그 부분도 확대 화면 넣어주세요.
- [x] 11:45 등등 화면 전환 하는 부분이 느리게 전환돼서... 전체적으로 속도 조절 부탁드려요.(00:30으로)
- [x] 12:20 이부분 -> 이 부분
- [x] 12:23, 12:48 확대화면 넣어주세요
- [x] 13:08 얘는 없는 게 나을 것 같은데, 일단 대표님 피드백도 한번 받아보고 결정하도록 할게요.

- [x] 16:35 추천에 update 나오는 것 볼 수 있게 확대 화면을 좀 왼쪽으로 옮겼으면 좋겠네요.
- [x] 16:23, 16:44 화면 전환이 느려서 그런건지 화면 전환 시 오디오 겹침 문제도 크네요. 
- [x] 16:47~16:49 원래 이런 소리 없는 black 화면이 있는 건가요? 실수라면 다음부터 좀 더 꼼꼼히 작업해주시고, 원래 있던거라면 그냥 없애주세요.
- [x] 17:14 짤 의미를 모르겠어요.
- [x] 17:19 이런 경우에는 시뮬레이터의 빈 공간을 이용해서 거기에 짤을 띄우는 것도 하나의 방법이에요.
- [x] 17:39 ~ 확대 화면들 타이밍이 이상한데요. 16:47 때문에 이렇게 된 것 아닌가 싶기도 하네요.
- [x] 24:05 이런 거 좋아요~
- [x] 24:32 효과 자막 움직임
       -> 파컷 내에서는 재생할 때 움직이지 않는데 영상에서만 움직이는 것 같습니다.
- [x] 25:43 말이 원래 이렇게 끊기나요? 깔끔하게 처리부탁드려요.
- [x] 28:55 안돼요 까지 이 자막 나오고 안돼요 할 때 엑스 표시 같은 거 추가해주세요. nope 같은 효과음도 넣어주시면 좋을 듯(해당 효과음 없으면 요청 바람)
- [x] 29:31 말풍선에 있는 글씨체 기존에 사용하던 글씨체 맞나요?
       -> 같이 다운 받았던 걸로 착각했던 것 같습니다 해당 글씨체 모두 변경하겠습니다
- [x] 30:12 이런 짤이 있다면 나중에 클레임이 들어올 수도 있을 것 같네요.
- [x] 32:15, 33:42, 34:20, 36:57 확대 화면
- [x] 34:36 2배속이라는 효과 자막 때문에 위에 입력하는 부분이 다 가려졌네요
- [x] 36:10 효과 자막 좀 덜 튀어 나가게 조절.
- [x] 39:01 에서 오타가 나서 44:12에서 문제 발견해서 해결하는데 이와 관련한 간단한 언급 있으면 좋겠어요.

- [x] 41:10 ~ 화면 확대, 3배속 해도 될 듯.
- [x] 41:43, 46:14, 49:24 화면 확대
- [x] 46:29 보면 cancel 연결 한 것 없어지고 save 연결하고 이름 넣고 다시 cancel 연결하는 것 나오는데 앞에 cancel 연결하는 부분 없애주세요.
- [x] 47:58, 52:37, 56:37 연결 자연스럽게
- [x] 49:41 auto completion도 볼 수 있게 화면 조정 부탁드려요.
- [x] 52:32 이때 화면 좀 아래로 내려가면 좋을 듯.
- [x] 57:39 오타고 나중에 고친다는 효과 자막 넣어주세요.
- [x] 59:24 너무 아래에 있어서 답답해요 좀 위로 올려주세요.
- [x] 1:06:19 확대 화면, 그리고 현재 수정중인 대상이 뭔지 화살표로 나타내 주세요.

- [x] 지난 번/이번 파컷 확인해보니까 화면 확대/축소 할 때마다 컴파운드 클립 만드셨던데 그렇게 하실 필요 없어요. 그냥 확대 시작/복구 하는 부분에 cross dissolve 효과 넣어주시면 돼요.

2차 편집 계획 by Yeonji

- [x]  0:00 "Higher~" 자막
- [x]  0:14 여러분이 만든 앱에도 테이블 뷰는 꼭 하나씩 들어갈 거에요 → 테이블 뷰 인싸 썬글라스 쓴 모습 아니면 적절한 짤에 테이블 뷰 이름표
- [x]  0:24 자 들어가 볼까요? → 후에 인트로 파컷
- 0:25 커스텀 셀
- [x]  0:30 테이블 뷰의 중급이라는 얘기죠? → "테이블 뷰 중급" 자막
- [x]  0:44 "커스텀 셀 만들기!" 자막
- [x]  1:04 허들이에요 → 각각의 허들 넘는 거 표현 가능하면 하기
- [x]  1:21 화이팅 짤
- [x]  1:55 "애플 문서 형식에 익숙해지자!" 자막
- [x]  3:03 sub title 셀 자료 화면
- [x]  3:40 sub title 셀 자료 화면에 이미지 부분 말풍선
- [x]  3:53 레이블 세 영역 표시
- [x]  4:27 커맨드+컨트롤+스페이스 자막표시
- [x]  5:30 화면 확대 말풍선
- [x]  5:43 핀 박는거 안보임 화면 추가
- [x]  5:59 화면 확대
- [x]  6:32 화면 확대 말풍선
- [x]  6:42 부터 셀이 어떻게 보이는지 말하실 때 화면 확대
- [x]  7:09 이걸 꼭 알아야하나 → 적절한 짤
- [x]  7:11 "Auto Layout에서 꼭 필요한 Hugging!" 자막
- [x]  7:20 "남아있는 공간을 누가 차지할 것인가?" 자막
- [x]  7:55 쎄게 안는 짤
- [x]  8:05 "Content Hugging Priority" 중요 단어 자막
- [x]  8:28 쎄게 안는다 = 우선순위가 높다
- [x]  8:37 "상대적인 숫자" 자막
- [x]  8:45 "Resistance Priority" 자막 + 작은 말풍선 "다음에!"
- 8:55 셀 서브 클래스
- [x]  9:26 "Outlet", "Action" 자막
- [x]  9:50 화면 확대
- [x]  10:30 화면 확대 말풍선
- [x]  10:45 화면 확대 말풍선
- [x]  11:18 화면 확대 말풍선
- [x]  11:24 화면 확대 말풍선
- [x]  11:42 "EmojiTableViewCell Class!" 자막
- [x]  ~12:17 화면 확대
- [x]  12:19 "이 부분 중요해요!" 자막
- [x]  12:30 화면 확대 말풍선
- [x]  13:04 적절한 짤 찾기
- [x]  13:15 화면 확대
- [x]  13:23 화면 확대
- [x]  15:06 셀은 그대로 이모지 셀이라는 아이덴티파이어가 붙어있겠죠 → EmojiCell 화살표
- [x]  15:12 그건 무조건 EmojiTableViewCell 일거야 → as! EmojiTableViewCell 밑줄
- [x]  15:42 좀 불편한데 → 짤
- [x]  15:58 새로 만들고 있죠 애플이 → 짤
- [x]  16:09 "UIKit" 자막
- [x]  16:19 화면 확대
- [x]  17:14 쫌 빡빡하네요 → 짤
- [x]  17:16 따를껄 그랬나 → 짤
- [x]  17:26 아래쪽에 디스크립션은 좀 작아야될 것 같죠 → 화살표
- [x]  17:38 화면 확대 말풍선
- [x]  17:54 화면 확대 말풍선
- 18:27 테이블 뷰의 편집
- [x]  18:46 "Editing Style" 중요 단어 자막
- [x]  19:15 "Editing Button의 Style"자막
- [x]  20:10 "canEditRowAt이 False이면 편집불가" 자막
- [x]  21:29 "유저 데이터 업데이트" 자막
- [x]  21:36 "추가, 삭제를 위해서는 반드시 구현해야한다" 자막
- [x]  22:02 작은 말풍선으로 위에는 "모델 업데이트", 아래에는 "UI적인 업데이트"
- [x]  23:36 "/* 주석입니다 */" 자막
- [x] 23:40 애플이 엄지척하는 짤
- [x] 23:53 셀 삭제되는 모습 표현
- [x] 24:12 "RowAnimation" 자막
- [x] 24:25 "automatic" 자막이나 말풍선 + 셀 왼쪽으로 푸시되는 모습
- [x]  25:12 화면 확대
- [x] 25:36 화면 확대
- 26:31 아이템 추가와 수정
- [x]  27:04 "자동 추가되고 그것이 의미를 가질 때" 자막
- [x]  27:47 "입력 폼 제작에 Static Table View를 쓴다" 자막
- [x] 28:14 좋은 예를 들고 있어요 책에서 → 짤
- [x]  28:47 "Static Table View를 만드려면 반드시 UITableView Controller 사용!" 자막
- [x] 28:43 상황을 주요 단어 자막으로 표현
- [x]  29:28 "데이터 소스 메소드들, Section의 개수, Row의 개수, 각 셀의 정보" 자막
- [x]  30:10 히그를 잘 못 이해하고 계시는데? → 짤
- [x]  30:34 "Modal → 짧은 Task, Push → 데이터 계층 구조에 맞는 것" 자막
- [x]  30:58 "상세한 정보 목록일 때 Push" 자막
- [x]  31:02 "수정하는 Task는 Modal" 자막
- [x]  31:54 "Constraint 넣는 것 잊지말자" 자막
- [x]  32:48 "Modal로 올라오는 것은 2층으로" 자막 + 작은 말풍선 "Tip!"
- [x]  33:17 화면 확대 말풍선
- [x]  33:30 화면 확대 말풍선
- [x]  33:39 화면 확대 말풍선
- [x]  33:53 화면 확대 말풍선
- [x]  33:58 화면 확대 말풍선
- [x]  35:15 0,0,0,0 설정 화면
- [x]  35:34 커멘드 쉬프트 H 를 누르면 홈버튼
- [x]  36:08 "Table View를 관리하는 Custom Class 필요!" 자막
- [x]  36:19 화면 확대
- [x]  36:35 화면 확대 말풍선
- [x]  37:10 화면 확대
- [x]  37:33 에딧이모지화살표 표시
- [x]  38:05 화면 확대
- [x]  40:10 "곧 보여요!" 작은 말풍선
- [x] 40:14 잡았다 요놈 짤
- [x]  41:39 "곧 보여요!" 작은 말풍선
- [x]  43:31 "변수 Shading" 자막
- [x]  45:11 "Save, Cancel 버튼 만들기!" 자막
- [x]  45:13 "어디로 가느냐의 문제" 자막
- [x]  45:29 소스 컨트롤러는 → 화살표
- [x]  45:49 화면 확대 말풍선
- [x]  46:16 화면 확대 말풍선
- [x]  46:32 화면 확대 말풍선
- 47:00 입력값 확인
- [x]  47:06 "Validation" 자막
- [x]  47:25 "fiilled" 자막으로 해당 부분 가리기
- [x]  48:00 화면 확대
- [x]  49:40 화면 확대
- [x] 50:16 오타 장면 삭제
- [x]  52:15 화면 확대
- [x] 52:45 이 방식이 베스트 프렉티스 → 짤
- [x]  55:39 화면 확대
- [x]  57:43 unwind segue 오타장면 지우기
- [x] 1:0042 optional 없어지는 부분 표시
- [x] 1:02:14 "마지막" 작은 말풍선
- [x] 1:02:44 으쓱 짤
- [x]  1:03:12 "여러 줄을 표시하기 위해 셀의 높이가 유동적이어야!" 자막
- [x]  1:04:00 이 부분 적절하게 자막넣기
- [x] 1:05:16 750 작은 말풍선
- [x] 1:05:23 "내부의 label에 따라 크기 결정", "외부의 cell의 크기에 영향" 자막
- [x]  1:06:05 화면 확대 말풍선
- [x]  1:06:49 화면 확대
- 1:07:57 LAB
- [x]  1:07:42 마지막이에요 → 짤
- [x]  1:09:00 제가 여러분들의 즐거움을 뺏지 않을게요 → 적절한 짤 찾기
- [x]  1:09:33 테이블 뷰 뽀개기 → 자막 or 짤
- [x]  1:09:49 축하드려요 → 짤
- [x]  1:59:11 여러분들은 뿌듯해 해도 되구요 → 짤
- [x]  마지막 OUTRO 파컷삽입

- 별 문제 없음. 바로 @manju-minji 님이 2차 편집 들어가 주세요.

**Comment by Yeonji-Lim** [comment]
2차 편집 계획 by Yeonji

- [x]  0:00 "Higher~" 자막
- [x]  0:14 여러분이 만든 앱에도 테이블 뷰는 꼭 하나씩 들어갈 거에요 → 테이블 뷰 인싸 썬글라스 쓴 모습 아니면 적절한 짤에 테이블 뷰 이름표
- [ ]  0:24 자 들어가 볼까요? → 후에 인트로 파컷
- 커스텀 셀
- [x]  0:30 테이블 뷰의 중급이라는 얘기죠? → "테이블 뷰 중급" 자막
- [x]  0:44 "커스텀 셀 만들기!" 자막
- [x]  1:04 허들이에요 → 각각의 허들 넘는 거 표현 가능하면 하기
- [x]  1:21 화이팅 짤
- [x]  1:55 "애플 문서 형식에 익숙해지자!" 자막
- [ ]  3:03 sub title 셀 자료 화면
- [ ]  3:53 레이블 세 영역 표시
- [ ]  4:55 스택 뷰 영역 표시
- [ ]  5:30 화면 확대 말풍선
- [ ]  5:43 핀 박는거 안보임 화면 추가
- [ ]  6:27 화면 확대 말풍선
- [ ]  6:32 화면 확대 말풍선
- [ ]  6:40 커맨드+컨트롤+스페이스 자막표시
- [ ]  6:42 부터 셀이 어떻게 보이는지 말하실 때 화면 확대
- [ ]  7:09 이걸 꼭 알아야하나 → 적절한 짤
- [ ]  7:11 "Auto Layout에서 꼭 필요한 Hugging!" 자막
- [ ]  7:20 "남아있는 공간을 누가 차지할 것인가?" 자막
- [ ]  7:55 쎄게 안는 짤
- [ ]  8:05 "Content Hugging Priority" 중요 단어 자막
- [ ]  8:28 쎄게 안는다 = 우선순위가 높다
- [ ]  8:37 "상대적인 숫자" 자막
- [ ]  8:45 "Resistance Priority" 자막 + 작은 말풍선 "다음에!"
- 8:55 셀 서브 클래스
- [ ]  9:13 셀안에 들어가는 것들 언급할 때마다 이미지 자료 추가
- [ ]  9:30 "1. outlet 2. action" 자막
- [ ]  9:50 화면 확대
- [ ]  10:30 화면 확대 말풍선
- [ ]  11:18 화면 확대 말풍선
- [ ]  11:24 화면 확대 말풍선
- [ ]  11:42 "EmojiTableViewCell Class!" 자막
- [ ]  ~12:17 화면 확대
- [ ]  12:19 "이 부분 중요해요!" 자막
- [ ]  12:32 화면 확대 말풍선
- [ ]  13:15 화면 확대 말풍선
- [ ]  13:23 화면 확대 말풍선
- [ ]  14:00 테이블 뷰 컨트롤러에서 셀에서 다 했던 것 → 자료 화면 추가
- [ ]  14:48 "UITableViewCell > EmojiTableViewCell" 자막
- [ ]  15:06 셀은 그대로 이모지 셀이라는 아이덴티파이어가 붙어있겠죠 → EmojiCell 밑줄
- [ ]  15:12 그건 무조건 EmojiTableViewCell 일거야 → as! EmojiTableViewCell 밑줄
- [ ]  17:14 쫌 빡빡하네요 → 짤
- [ ]  17:16 24로 할 껄 그랬나 → 자료화면: 이전에 24로 설정했던 화면
- [ ]  17:26 아래쪽에 디스크립션은 좀 작아야될 것 같죠 → 화살표
- [ ]  17:38 화면 확대 말풍선
- [ ]  17:54 화면 확대 말풍선
- 18:27 테이블 뷰의 편집
- [ ]  18:46 "Editing Style" 중요 단어 자막
- [ ]  18:56 지난시간에 none으로 설정한 자료화면
- [ ]  19:53 "canEditLowAt" can만 색깔 바꾸어서 강조
- [ ]  21:29 "유저 데이터 업데이트" 자막
- [ ]  21:36 "추가, 삭제를 위해서는 반드시 구현해야한다" 자막
- [ ]  22:02 작은 말풍선으로 위에는 "모델 업데이트", 아래에는 "UI적인 업데이트"
- [ ]  22:10 잘만드는 케이스 → 적절한 짤?
- [ ]  23:36 "/* 주석입니다 */" 자막
- [ ]  25:20 - 26:14 화면 확대
- 26:31 아이템 추가와 수정
- [ ]  27:47 "입력 폼 제작에 Static Table View를 쓴다" 자막
- [ ]  28:47 "Static Table View를 만드려면 반드시 UITableView Controller 사용!" 자막
- [ ]  29:28 "데이터 소스 메소드들, Section의 개수, Row의 개수, 각 셀의 정보" 자막
- [ ]  29:33 지우는 것 처럼 자막에 X표시
- [ ]  29:49 화면 확대
- [ ]  30:10 히그를 잘 못 이해하고 계시는데? → 짤
- [ ]  30:30 잘못된 부분 X 표시
- [ ]  30:34 "Modal → 짧은 Task, Push → 데이터 계층 구조에 맞는 것" 자막
- [ ]  30:58 "상세한 정보 목록일 때 Push" 자막
- [ ]  31:02 "수정하는 Task는 Modal" 자막
- [ ]  31:54 "Constraint 넣는 것 잊지말자" 자막
- [ ]  32:48 "Modal로 올라오는 것은 2층으로" 자막 + 작은 말풍선 "Tip!"
- [ ]  33:17 화면 확대 말풍선
- [ ]  33:30 화면 확대 말풍선
- [ ]  33:39 화면 확대 말풍선
- [ ]  33:58 화면 확대 말풍선
- [ ]  34:03 화면 확대 말풍선
- [ ]  34:19 화면 확대 말풍선
- [ ]  34:40 화면 확대 말풍선
- [ ]  34:57 Inset Grouped가 더 예쁘네요 → 짤
- [ ]  35:15 0,0,0,0 설정 화면
- [ ]  35:34 커멘드 쉬프트 H 를 누르면 홈버튼
- [ ]  36:08 "Table View를 관리하는 Custom Class 필요!" 자막
- [ ]  36:19 화면 확대
- [ ]  36:35 화면 확대 말풍선
- [ ]  37:10 화면 확대
- [ ]  38:05 화면 확대
- [ ]  40:10 "곧 보여요!" 작은 말풍선
- [ ]  41:39 "곧 보여요!" 작은 말풍선
- [ ]  43:31 "변수 Shading" 자막
- [ ]  45:11 "Save, Cancel 버튼 만들기!" 자막
- [ ]  45:29 소스 컨트롤러는 → 화살표
- [ ]  45:49 화면 확대 말풍선
- [ ]  46:16 화면 확대 말풍선
- [ ]  46:32 화면 확대 말풍선
- 47:00 입력값 확인
- [ ]  47:06 "Validation" 자막
- [ ]  47:25 "fiilled" 자막으로 해당 부분 가리기
- [ ]  48:00 화면 확대
- [ ]  49:40 화면 확대
- [ ]  51:28 화면 확대
- [ ]  52:15 화면 확대
- [ ]  55:39 화면 확대
- [ ]  57:11 unwind segue로 매치가 되어있네요 → 정확히 어디인지 화살표
- [ ]  57:29 저런 이름은 그때그때 바뀔 수가 있거든요 → 화살표
- [ ]  1:03:12 "여러 줄을 표시하기 위해 셀의 높이가 유동적이어야!" 자막
- [ ]  1:04:00 이 부분 설명을 좀 더 알아보기 쉽게 가능?
- [ ]  1:06:19 화면 확대 말풍선
- [ ]  1:06:33 화면 확대 말풍선
- [ ]  1:06:49 화면 확대
- [ ]  1:07:29 화면 확대 말풍선
- 1:07:57 LAB
- [ ]  1:09:00 제가 여러분들의 즐거움을 뺏지 않을게요 → 적절한 짤 찾기
- [ ]  1:09:33 테이블 뷰 뽀개기 → 자막 or 짤
- [ ]  1:09:49 축하드려요 → 짤
- [ ]  1:59:11 여러분들은 뿌듯해 해도 되구요 → 짤
- [ ]  마지막 OUTRO 파컷삽입

**Comment by lingostar** [comment]
@manju-minji 님, 마지막 피드백 드렸어요
