### ISSUE TITLE
드림인 iOS 아카데미 홍보글 

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#208]
아래와 같이 페이스북에 홍보글을 올려주세요.

지난 [드림인 iOS 아카데미]의 10개 앱 프로젝트 중 앱 스토어에 등록된 5개 앱을 소개합니다.
앞으로 차근차근 코더스하이 수강생의 앱을 소개하는 시간을 가져보겠습니다.

전체 페이지 링크 (자동 생성되는 대표 이미지에 신경 써 주세요)
Waha : 링크
GAK : 
Vridge : 
Switching : 
모그리지 :

**Comment by jin0yoon** [comment]
Waha : https://apps.apple.com/us/app/wa-ha/id1542286897
 GAK :  https://apps.apple.com/us/app/gak/id1541343166
Vridge : https://apps.apple.com/us/app/vridge/id1541849378 
Switching :  https://apps.apple.com/us/app/%EC%8A%A4%EC%9C%84%EC%B9%AD/id1542290155
모그리지 : https://apps.apple.com/us/app/%EB%AA%A8%EA%B7%B8%EB%A6%AC%EC%A7%80/id1541566943

**Comment by lingostar** [comment]
@yeongjinlee 님, 진영님과 함께 페이스북 홍보 글을 만들어 주세요. 일단 비공개로 만들어서 공유주시면 제가 확인 후 공개로 전환할께요.

이 티켓에 영진님이 필요한 이유는,  외부에 보이는 글이기 때문에 대표이미지 등에 약간 신경을 써 주길 바라기 때문. 
페이스북과 링크드인에 동일한 내용이 올라가야 합니다.
