### ISSUE TITLE
동국대학교 2021 iOS ML 과정 소개 글

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#209]
아래와 같이 페이스북에 홍보글을 올려주세요.

지난 겨울방학 동국대학교에서 열린 iOS ML 과정의 9개 앱 프로젝트 중 5개가 앱 스토어에 등록되었습니다. 
우와 우와~~~  🎉🎉🎉🎉🎉🎉

55%의 앱 등록율이라니, 이런 연쇄 출앱마 같으니라구 😄
어떤 앱 이 앱스토어에 등록되었는지 차근차근 코더스하이 수강생의 앱을 유튜브를 통해 소개하는 시간을 가져보겠습니다.

전체 페이지 링크 (자동 생성되는 대표 이미지에 신경 써 주세요)
바른
유니캘린더
스토커
널스케쥴
펫디

**Comment by jin0yoon** [comment]
바른 : https://apps.apple.com/us/app/%EB%B0%94%EB%A5%B8/id1552030717
유니캘린더 : https://apps.apple.com/us/app/%EC%9C%A0%EB%8B%88%EC%BA%98%EB%A6%B0%EB%8D%94/id1555101858
스토커 : https://apps.apple.com/us/app/%EB%98%91%EB%98%91%ED%95%9C-ai-%ED%8E%80%EB%93%9C%EB%A7%A4%EB%8B%88%EC%A0%80-stocker/id1550061852
널스케줄 : https://apps.apple.com/us/app/%EB%84%90%EC%8A%A4%EC%BC%80%EC%A4%84/id1552664387
펫디 : https://apps.apple.com/us/app/%ED%8E%AB%EB%94%94/id1551631046
