### ISSUE TITLE
주목할만한 앱 추가

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#210]
주목할만한 앱으로 추가하는 것은 다음 기준

- 앱스토어에 올라간 앱은 🎊를 앞에 달고 일단 추가
- 앱스토어 올라가지 않은 앱도 좋은 앱은 추가
- 주목할만한 앱들은 모두 Students 그룹을 Read 권한으로 추가.
- 연도내 앱 정렬은 좋은 앱 순서로.

**Comment by jin0yoon** [comment]
동국대학교 iOS ML 2021
드림인 iOS 아카데미
한양대 SW스튜디오 2020
한동대 특강 2020
온라인스쿨 3기
