### ISSUE TITLE
SwiftUI 플레이그라운드 북

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#212]
프로토타입 과정의 후반부 교재인 SwiftUI 플레이그라운드 북의 완성

**Comment by jin0yoon** [comment]
3/5(금) 회의 내용
- 전체 구조 변경
   - 예제는 기존에 만들던 SwiftUI UX Design Book의 예제로 사용
   - 페이지를 좀 더 세분화하여 분리할 것
   - 지금은 너무 정보 나열식으로 되어있음 -> 이용자가 직접 코드를 작성해보고 수정할 수 있도록 유도하도록 변경
       - 흥미를 느낄 수 있도록 하는 것이 중요
   - 각 챕터의 마지막에 해당 챕터에서 배운 것들을 활용할 수 있도록 하는 project 페이지로 구성
       - 예제로 만든 앱의 화면을 캡쳐해서 보여주고 이 화면을 만들어보도록 함
  
- 일정 : 3월 말까지 1차 완성 후 링고님께 피드백. 4월 말까지 최종 완성

- 다음 회의 : 3/12 (금) 오후 4시

- 다음 회의까지 할 일
   - 진영 : 챕터, 페이지 구조 잡기
   - 주훈 : 기존에 만들던 SwiftUI UX Design Book 만들어지지 않은 부분 채우기

**Comment by jin0yoon** [comment]
3/12 회의 내용
- 구조 예시
  1. 목표
  2. Text에 대한 기본 설명
  3. 기본 코드 예제 따라해보기
  4. 실행 후 결과 확인 (메모 원하는 경우 메모 작성)
  5. modifier에 대한 설명
  6. 값 변경 및 새로운 modifier 적용해보기
  7. study tip (해당 페이지와 관련된 내용에 대해 google 키워드 제공)
![스크린샷 2021-03-12 오후 3 52 25](https://user-images.githubusercontent.com/64063225/110903611-0e432780-834b-11eb-8684-39a1959203b4.png)
![스크린샷 2021-03-12 오후 3 52 37](https://user-images.githubusercontent.com/64063225/110903621-11d6ae80-834b-11eb-8084-afe1a2eb0119.png)
![스크린샷 2021-03-12 오후 3 52 48](https://user-images.githubusercontent.com/64063225/110903633-14d19f00-834b-11eb-97c3-975148ed8b6f.png)

- 각 챕터 마지막에 project 페이지
   - 이미지를 보여주면서 구현해보라고 유도
   - HintView를 통해 힌트 볼 수 있도록
       - 힌트 내부 코드는 보지 못하게
       - 우선 사용자가 스스로 풀어보고
       - 버튼이나 disclosuregrop을 사용하여 사용자가 원하는 경우 힌트를 볼 수 있도록
![스크린샷 2021-03-12 오후 3 53 02](https://user-images.githubusercontent.com/64063225/110903637-169b6280-834b-11eb-82a6-04e36d10f5ac.png)

- 일정 : 3월 말까지 1차 완성 후 링고님께 피드백. 4월 말까지 최종 완성

- 다음 회의 : 3월 29, 30, 31 중 하루 잡아서 할 것 (정확한 날짜 및 시간은 추후 결정)

- 다음 회의까지 할 일
   - 진영 : Chapter1 완성. 주훈님이 완성한 Chapter2, 3 검토 및 수정 + 주훈님이 일정 맞추기 어려운 경우 백업하기
   - 주훈 : Chapter2, 3 완성 (한주에 Chapter 1개씩을 목표로) -> 다음주 주말부터 작업 시작 가능
