### ISSUE TITLE
DUNS Number 생성

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#213]
코더스하이의 DUNS Number를 받아서 
현재 앱스토어 Lingostar 계정을 CodersHigh 계정으로 전환

현재는 개인회사 등록이 막혀있음. 난 오래전에 해서 개인이지만 회사이름 사용 중.

무역 확인용 번호. 한국에서는 NICE D&B 가 유료로 신청을 받음. (수수료 비쌈)

**Comment by jin0yoon** [comment]
https://developer.apple.com/kr/support/D-U-N-S/
https://developer.apple.com/enroll/duns-lookup/#!/search

법인명 
본사 주소
우편 주소
회사 연락처 정보

확인 절차의 일부로 D&B 담당자가 귀하에게 직접 업종, 직원 수와 같은 추가 정보를 문의할 수도 있습니다. 사업자 등록 서류를 준비해 두시기 바랍니다.

D-U-N-S 번호 요청 후 D&B로부터 번호를 발급받는 데는 업무일 기준으로 최대 5일이 걸립니다.
귀하가 D-U-N-S 번호를 발급받은 후 Apple이 귀사의 정보를 D&B로부터 받는 데는 업무일 기준으로 최대 2일이 걸립니다.
이 기간이 지나면 Apple Developer Programs에 회사/기업으로 등록할 수 있습니다.

**Comment by jin0yoon** [comment]
- DUNS Number 생성 요청 완료했습니다.
![스크린샷 2021-03-03 오후 1 53 57](https://user-images.githubusercontent.com/64063225/109754723-e9063900-7c27-11eb-83dc-f0c00aa17047.png)

**Comment by jin0yoon** [comment]
![스크린샷 2021-03-03 오후 2 16 14](https://user-images.githubusercontent.com/64063225/109756291-04bf0e80-7c2b-11eb-80a6-c030ed90ad6e.png)
