### ISSUE TITLE
앱스토어 계정 법인 전환

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#214]
#213 이슈 해결 후 진행.

애플의 개인->법인 계정 전환에 대해 리서치하고 Lingostar -> CodersHigh 전환

**Comment by jin0yoon** [comment]
회사 이름 변경을 계속 진행하시려면 LingoStar 개발 팀의 계정 소유자께서 다음 페이지를 통해 이 요청을 다시 제출하도록 해 주십시오.
https://developer.apple.com/contact/submit/?entityType=company&requestType=updateInformation

**Comment by jin0yoon** [comment]
기업 -> 기업으로는 계정 전환 불가 (개인 -> 기업으로는 가능)
앱 이전하게 되면 이전 받은 계정은 중소기업 혜택 받지 못함
