### ISSUE TITLE
코더스하이 학생부 정리

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#215]
2015년 고려대학교 방학특강부터
2021년까지 코더스하이 수업을 들었던 학생들의 정보에 대한 기록을 남김.

나중에 코더스하이 수료증 발행과 연관이 있음.

**Comment by jin0yoon** [comment]
동국대 2021까지 명단 정리 완료
2016년과 2017년 업데이트 필요 (2016 겨울 고려대, 2016 1학기 서울대는 명단 정리 완료)
