### ISSUE TITLE
UIKit + SwiftUI 자료정리

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#221]
이 티켓에 관련 정보들을 정리하고 예제를 만들어봅시다.

**Comment by jin0yoon** [comment]
### Architecture
![스크린샷 2021-03-09 오후 5 45 53](https://user-images.githubusercontent.com/64063225/110443504-53731980-80ff-11eb-80b8-2a44b1a61c57.png)

Step 1. 구현하고자 하는 SwiftUI 화면 구현

Step 2. UIHostingController (https://developer.apple.com/documentation/swiftui/uihostingcontroller)
`class UIHostingController<Content> where Content : View`
- SwiftUI view hierarchy를 관리하는 UIKit view controller
- SwiftUI View 렌더링 및 전체 View의 lifecycle을 관리
- SwiftUI View를 띄울 기존의 UIKit ViewController와 연결되는 부분

Step 3. 기존의 UIViewController와 UIHostingController 연결
(ex) 버튼 클릭 시 UIHostingController present

Step 4. SwiftUI view의 data, logic 부분 구현을 위한 ViewModel 구현

Step 5. UIHostingController와 ViewModel 연결
