### ISSUE TITLE
Oldies but Goodies 정리

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#241]
코더스하이의 비디오 콘텐츠 자산으로 다음과 같은 고전이 있습니다.

KT ECNV  비디오 : 2010년 제작
Pomodoro 만들기 비디오 : 2013년 제작
Programmers  비디오 : 2017년 제작

이 중 Programmers 는 2020년에 독점 배포권이 끝났고 , Pomodoro는 그냥 내가 만든 거.
ECNV 는 계약 관계 확인 요.

이걸 게더의 어딘가에 아카이브 하고, 
유튜브 스위프트 하이에 올리는 것에 대해 어떻게 생각하나요?

**Comment by jin0yoon** [comment]
Programmers 영상은 올리는 것이 좋을 것 같습니다. 게더에도 아카이브하면 좋을 것 같습니다.
KT ECNV, Pomodoro 만들기 비디오는 너무 예전 영상이라 올리지 않는 것이 좋을 것 같습니다.
