### ISSUE TITLE
Hall of Fame

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#247]
Hall of Fame 을 완성합니다.

현재 학습지는 지난 번에 리스트업한 분들의 학습지를 적절한 방법으로 공유해 주세요.

페이스북 광고로도 만들 예정이니, 웹에서 바로 접근가능한 방법도 있어야 합니다.

드라이브의 '코더스하이_일반업무' 에 임정상님의 HTML 파일이 있어요.

**Comment by jin0yoon** [comment]
Gather Hall of Fame 완성

링크
4기 박형석님
https://docs.google.com/document/d/e/2PACX-1vRp3RijBqzry1xpshLxQOqkYx3eTx0T2slpBHJKYhgLGrGaROcQ2_0w5oUHTh2n7oTRLs6I0wept9ow/pub
4기 임정상님
https://docs.google.com/document/d/e/2PACX-1vTqetXLSLA_qU5gXvW3wr0-ShTHr3HGj0wj6xOeZFHvsjQRxcuA0qrRGnfIjwYr-WxUOT4XY8q6J6zQ/pub
4기 이건우님, 이로운님
https://docs.google.com/document/d/e/2PACX-1vQN57smpqBHp4nL64WZZiLAk19dGJcPXbe9WuVrDEz_vJr4JP6tUn_ArtVtl1bWQ53vbch8mDeVLGds/pub
