### ISSUE TITLE
005 전문가를 소개합니다.

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#26]
1차 피드백

- 처음에 파프리카 우리 아들 빵터짐 ㅋ
- [x] 4:53 자막이 너무 길어요. 두개로 나눠줘요.
- [x] 5:49 맵 볼때 캠 화면으로 전환 한 번 해 주세요 -> 코딩 시작할 때 캠 화면 나오네요. 그거 유지하고 이건 짧게라도 가죠. 
- [x] 06:07 내가 하는 말은 "재사용 가능" 이예요. 효과자막 그렇게 넣어도 되지 않을까요?
- [ ] 09:50 구독 좋아요 공유 효과자막 써 주세요.
- [x] 마지막에 화면 흔들리는 거 빼 주세요.

**Comment by lingostar** [comment]
@aawlgus96 1차피드백 했어요

**Comment by aawlgus96** [comment]
구독 좋아요 공유 나갈 동안에 구독버튼이랑 종료화면 동영상 띄우는건 어떨까요?
화면에 효과자막이 나가다보니까 그 타이밍에 종료화면 구성하기가 힘들것 같아서요!

**Comment by lingostar** [comment]
@aawlgus96 네, 그렇게 하세요
