### ISSUE TITLE
007 매개변수

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#28]
**1차 피드백**
- [x] 00:16 갑자기 손 나오는 거 깜짝 놀라요. ㅋ 잘라주세요~ 
- [x] 01:26 읽기 쉬워진다는 자막도 넣어주세요. 의미가 있는 멘트예요.
- [x] 04:30 무브하고 돌고 막 하는 게 계속되니까 눈으로 따라가기 어려워요. 점 하나 찍어주세요. 회전시엔 변화 없겠지만 몇 칸 옮기면 어디로 가는 건지 알 수 있게
- [x] 킵 고잉 나오는 타이민 조금 느려요

**2차 피드백** 
- [x] 컷씬에서 좀 끊기는 느낌이 나네요
- [x] 02:50 정리해 -> 정의해

**Comment by lingostar** [comment]
@aawlgus96 1차 피드백 완료

**Comment by lingostar** [comment]
@aawlgus96 2차 피드백 보냈어요. 이제 바로 올려주세요.

**Comment by aawlgus96** [comment]
네 업로드 했습니다!!
