### ISSUE TITLE
019_Enum & Switch

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#31]
**1 차 피드백**
- [x] 01:48 주는 대로
- [x] 03:25 예요
- [x] 06:10 아메리칸 풋 볼에 대한 조사를 좀 하고 응대를 좀 해 주세요.
- [x] 07:31 불쾌ㅔ하지 않은 지저분한 짤을 찾아주세요 ㅋ
- [x] 08:18  문법적으로 switch가 나올 때는 항상 소문자
- [x] 10:16 채우는 -> 태우는
- [x] 12:25 사우th 아닌가요?

완료

**Comment by lingostar** [comment]
@manju-minji 피드백 완료

**Comment by manju-minji** [comment]
인트로 - enum의 필요성 - enum - enum과 함수 - 스위치 - enum method & property - exercise - 연습문제 - 아웃트로

어떠세요?

**Comment by lingostar** [comment]
@manju-minji enum의 필요성 - enum 을 enum 으로 합칩시다. 스위치

**Comment by manju-minji** [comment]
인덱스 포함해서 다시 영상 올렸습니다!

**Comment by manju-minji** [comment]
일단 파컷 파일도 올렸어요!
