### ISSUE TITLE
020_Final Project

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#32]
**1차 피드백**

- [x] 05:11 하겠네요 -> 타겠네요. 이건 내 말 습관. 어떤 값을 스위치 문에 태운다는 표현을 많이 써요.
- [x] ~ 11:44 이즈음에서 집중력이 팍 떨어지네요. 왼쪽편에 UI 그림 가져다 놓고 표시해 주면서 설명합시다.
- [x] 12:34 이때 놀리면 안돼요. 때 적절한 짤방 요~!
- [x] 14:32 효과자막으로 "코더스하이 리뷰 과정"
- [x] 15:25 스마일리 한글로 써 주구요, 😉🙂😝😄😃 이런식의 스마일리 예를 들어주세요.
- [x] 16:46 이때는 제가 Aspect Fill 이 낫지 않겠나? 라고 설명하는 중이예요.
-> 이대로 설정하면 좌우가~ 이 부분에서 그래도 Aspect Fill이 좋을 듯! 이라는 식으로 자막 넣을까요?
- [x] 16:55 pin 메뉴
- [x] 17:12 ~ 17:22 아울렛 연결할 UI에 빨간 밑줄 긋는 것 좋은데, 이왕이면 UI와 연결선도 그려주면 더 이해가 잘 되겠어요.
-> 일단 선 없는게 더 깔끔해보여서 없이로 해봤어요!
- [x] 19:22 세그먼티드 컨트롤을 그래픽으로 넣어주세요.
- [x] 19:44 '저 코드' 영역을 화면에 표시해 주세요
- [x] 20:20 코더스하이 과정 동일한 효과자막

피드백 완료

- [x] 14:50 사용할

**Comment by lingostar** [comment]
@manju-minji 1차 피드백 완료했어요

**Comment by manju-minji** [comment]
인트로 - 가위바위보 게임 로직 - 가위바위보 게임 UI - 짤 만들기 - 회고&summary - 아웃트로

어떠세요?

**Comment by lingostar** [comment]
가위바위보 게임 로직 - 가위바위보 게임 UI - 짤 만들기 가 사실상의 핵심인데, 
짤 만들기를 두 부분으로 나눌 분량은 안되나요?

**Comment by manju-minji** [comment]
가위바위보 게임은 로직, UI부분의 구분이 명확한데 짤만들기는 그닥 명확하지가 않은 것 같아요ㅠㅠ 다른 기준으로 나누면 ㅇㅇ넣기 ㅇㅇ배열하기 스택뷰이용하기 배열 이용하기 이런식으로 너무 세세해질것 같고요ㅠㅠ

**Comment by manju-minji** [comment]
16:46 이때는 제가 Aspect Fill 이 낫지 않겠나? 라고 설명하는 중이예요.
-> 이대로 설정하면 좌우가~ 이 부분에서 그래도 Aspect Fill이 좋을 듯! 이라는 식으로 자막 넣을까요?

이거 답변해주세용!

**Comment by lingostar** [comment]
@manju-minji 16:46은 Aspect Fill이 낫다고 보는데, 책에서 Aspect Fit을 하라니까 따라가는 거거든요.

**Comment by lingostar** [comment]
@manju-minji 그럼 인덱스를 나눈다면, UI 구성하기 - 타입 만들고 합치기

**Comment by manju-minji** [comment]
좋아용!!!!!

**Comment by manju-minji** [comment]
인덱스 포함해서 영상 올렸어요!
