### ISSUE TITLE
2019 한양대학교 정보

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#33]
2019년 1학기 한양대학교 결과물 정리 부탁해요.
참고로 한양대 영상 편집은 윤종원학생이 했습니다.

결과물의 순서는 아래와 같습니다.

민쯩이
QueOrder
한양과제알리미
Iffy
안주나요
AboutHanyang
연인캘린더
CheckHome

- [x] 전공&학년 무관 -> SW 스튜디오 (컴퓨터/SW 3학년 전공과목)
- [x] 기간 : 2019년 3월 ~ 2019년 6월
- [x] 시간 : 주 5시간, 총 75시간
- [x] 인원 : 수료율 100%
- [x] 강사 : 윤성관 | 이재훈
- [x] 위 순서 지켜주세요.

**2차 피드백**
- [x] 교육과정 시간을 25시간과 50시간으로 해 주세요.
- [x] 수료학생 수는 맞나요? 저거 별 의미 없지만 24명으로 해야 할 것 같은데요.
- [x] 순서가 다르고 이미지가 하나도 없어요
- [x] 앱스토어 링크와 웹 페이지 링크도 없네요

- [x] 홈 페이지에 보면 2018 한양대학교 iOS 특강 이라는 게 있는데, 공과대학~~~ 으로 맞춰주세요

**Comment by lingostar** [comment]
- [ ] 교육과정 시간을 25시간과 50시간으로 해 주세요.
- [ ] 수료학생 수는 맞나요? 저거 별 의미 없지만 24명으로 해야 할 것 같은데요.
- [ ] 순서가 다르고 이미지가 하나도 없어요

**Comment by lingostar** [comment]
@PACMAN-X 결과물이 하나도 안 보임

**Comment by lingostar** [comment]
아.. 오래 걸리는 거군요, Vue.js의 특징일까요?

**Comment by PACMAN-X** [comment]
특징은 빠른 것이 특징인 것인데.. ㅠㅜ 조금 살펴 보겠습니다.

**Comment by lingostar** [comment]
@PACMAN-X Summary 에서 인원 : 24명 (100%)
