### ISSUE TITLE
002_Unit1_1_Intro to Swift and Playground

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#44]
**1차 피드백**

- [x] 01:01 유튜브 안내 들어가려 할때, 효과자막으로 "좋은 말씀 전하러 왔습니다" 랑 성스러운 표정.. 그 프로듀스 101 사회자가 드라마에서 짓던 표정같은 짤방 있으면 잼있을 듯.
- [x] 07:08 이...이렇게 슬쩍 넘어가는 겨?
- [x] 07:12 문제 읽어나갈때는 보기가 미리 화면에 보여야 갑갑하지 않을 것 같아요.

좋네요. 웃겼어요 ㅎ

**2차 피드백**
- [x] 00:50, 00:58 삐 소리와 함께 검은 화면이 나오는 건 좀 극적인 상황에서만 씁시다. 저 2 곳은 모두 해당하지 않는것으로. (01:50쯔음의 삐- 는 괜찮아요)
- [x] 사진 자체는 재미있는데, 맥락이랑 좀 떨어져 있어요. 지금 필요한 짤은 영업사원, 광고, 도를 아십니까? 같은 느낌이 아닐까 싶어요.
- [x] 06:53 플레이그라운드에 대한 자료화면이 없던가요? ... 너무 글자와 말만 나오니 어려워 보여서
-> 대표님이 따로 넣어놓으신건가요?
-> 제가 넣은 기억은 없네요. 혹시 IntroAppDev에 사용한 장면들 몇 개 끌어다가 보여줄 수 있을까요?
-> 인트로앱데브에서 마땅한 걸 못찾겠어서 그냥 제가 임의로 상황에 적합하다고 생각하는 코드 작성해서 넣어봤는데 어떤까요!!

**3차 피드백**

- [x] 01:14 중간에 검은 화면이 나오네요.
- [x] 03:48 방법이예요
- [x] 05:21 데요

**Comment by lingostar** [comment]
@manju-minji 1차 피드백 완료했어요. 다음번엔 인덱스만 확인하면 되겠네요.

**Comment by manju-minji** [comment]
웃겼다니 매우 뿌듯하네용!! 피드백 반영 & 인덱스 포함 업로드 했습니당!

**Comment by lingostar** [comment]
@manju-minji 2차 피드백 줬어요

**Comment by manju-minji** [comment]
질문에 답변 부탁드려요옹!

**Comment by lingostar** [comment]
@manju-minji 답변했어요.

**Comment by lingostar** [comment]
@manju-minji 수정 요청 줬어요. 이거 수정하고 바로 백업으로 들어갑시다

**Comment by manju-minji** [comment]
파컷 파일 업로드 했습니다!
