### ISSUE TITLE
003_Unit1_2_Constants, Variables and DataTypes

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#45]
**1차 피드백**

- [x] 03:09 "원래 그런거야" 같은 짤방 하나 부탁해요
- [x] 10:12 3배속... 너무 빠른데?! 2배속으로 하는 건 어때요? 완전 의미없는 내용은 아니라서

2차 피드백
- [x] 01:08 기본이예요
- [x] 03:11 best practices 책에서 밑줄 그어 주세요. 화면 중간쯤에 있어요

2차 피드백 완료

**Comment by lingostar** [comment]
@manju-minji 1차 피드백 마쳤어요

**Comment by manju-minji** [comment]
피드백 반영 영상 올렸어요!!

**Comment by lingostar** [comment]
@manju-minji 2차 피드백은 영상 추출하지 말고 바로 파컷 파일 올려주세요

**Comment by manju-minji** [comment]
업로드했습니댜!
