### ISSUE TITLE
007_Unit1_6_Building, Running, and Debugging an App

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#47]
**1차 피드백**
- [x] 00:02, 00:05, 00:36, 00:45, 01:35, 02:14, 02:27, 02:35, 02:38, 02:49, 02:59, 03:40, 03:48, 04:57, 05:13, 05:30, 05:35, 05:43, 05:51, 06:01, 06:56, 07:00, 07:12, 07:15, 07:20-07:21, 07:43, 08:15, 08:26, 08:29, 08:33, 08:36, 08:40, 08:53, 09:04, 10:16, 10:35, 10:42, 10:48, 10:58, 11:02, 11:23, 11:26, 11:33, 11:38, 11:50, 12:14, 12:19, 13:12, 13:25, 13:29, 14:08-14:11, 14:30, 14:58, 15:02, 15:09, 15:16, 15:24, 15:40, 16:08, 16:13, 16:26, 16:32 : 쩝 소리, 숨소리, 음소리, 어소리 등 흐름이 느려지는 부분, 소리가 튀는 부분 좀 더 컷팅해주세요.(이거 말고도 전체적으로 흐름이 느려지는 부분이 많은 것 같아요)
- [x] 00:15 : 화면 나오고 자막 나오는 것 같은데 둘이 동시에 나오게 해주세요.
- [x] 01:49 : 효과 자막(제일 왼쪽 것)을 화면 안쪽으로 조금 이동 시키는게 좋을 것 같아요.(조금 튀어나와 있어서)
- [x] 03:18 - 03:22 : 검은 화면 나와요.
- [x] 04:15 - 04:18 : 말이 없는 부분이라 이 부분은 자르고, 스크로를 좀 더 뒤에 하던가 앞에 하면 좋을 것 같아요.
- [x] 04:36 - 04:38 : 화면이 아래로 움직여요.
- [x] 04:45 - 04:48 : 검은 화면에 (연결 중) 이런식으로 하고 넘기던가 배속을 하던가 하는 식으로 빨리 넘기는 게 좋을 것 같아요.
- [x] 05:37 : 네트워크 에 -> 네트워크에
- [x] 06:28 - 06:29 : 화면 전환이 이상해요.
- [x] 06:30 - 06:31 : breakpoint가 자막에 두번 나와요.
- [x] 06:44 - 06:45 : 밑줄 선이 끝까지 안 그어져 있어요.(전반적으로 거의 글자보다 선이 짧은게 많은 것 같아요.)
- [x] 07:43 : complie error 이게 너무 위에 있어요. 나중에 인덱스 넣을 때 문제 생길 수도 있어요~
- [x] 09:10 - 09:38 : 예제 만드는 부분이 좀 지루해요. 이 부분을 2배속으로 재생하고 자막에 '예제 만드는 중' 뭐 이런식으로 위쪽에 넣어주면 좋을 듯 해요.
- [x] 09:42 - 09:50 : 이 부분도 배속하고 'ㅇ배속 중' 이런식으로 자막 넣으면 좋을 듯.
- [x] 11:44 - 11:47 : 이 부분도 배속하거나 좀 자르거나 하는 게 좋을 듯.
- [x] 12:04 - 12:07 : 말 안하는 부분 잘라주세요(음성만)
- [x] 13:14: 여기 보시면 어 이건 ~ 이 부분을 여기 보시면 / 어 이건 ~ 으로 잘라주세요. 어 이건~ 부분을 따음표 효과 자막으로 넣어도 좋을 듯.
- [x] 13:46 - 13:51 : 자르던가, 배속처리하던가, 다른 음성 부분으로 옮기던가. 
- [x]  14:37 - 14:39 : 방황하는 마우스 삭제해도 될 듯.
- [x]  15:42 : 처음부터 15:44의 화면 위치대로 두는 게 좋을 듯.
- [x]  15:57 : 문제 해석은 음성 그대로 따라갈 필요없고 좀 더 다듬는게 좋을 것 같아요.(ex. 실제 기기에서 코드를 실행시키기에 필요한 것은? 이런식으로)

처음이신데 수고 많으셨어요! 기대 이상으로 잘해서 놀람! 화이팅!
그리고 nas에 001파일 보시면 인트로, 아웃트로 영상 언제 넣으면 되는지 볼 수 있으니까 그거 확인하시고 넣으시면 될듯요~!

2차 피드백 - 윤

- [x] 오디오에 효과 넣었나요? 소리가 먹힌 느낌. 답답하게 느껴지니 빼 주세요.
- [x] 03:08? 띵~ 할때 자기 폰 확인한 사람 손~! .-> 이걸 삭제하라는 게 아니라 재밌게 잘 살려주세요.
- [x] 04:17 어카운트 철자
- [x] 04:25 화면 깜빡임
- [x] 04:28 장면 전환하자마자 화면이 바뀌면 어떡해요. 뭔가가 사라진 후의 화면으로 연결해 주세요. 필요하면 오디오/비디오 분리. 
- [x] 04:54 프로비저닝 프로파일 아이콘 구해서 넣어주세요. 앞 부분 Certificate도 가능한 아이콘을 꺼내서 사용해 주세요.
- [x] 05:03 61페이지를 잠깐이라도 보여줘야 시청자들이 안 궁금하죠
- [x] 05:27 마찬가지로 62페이지를 잠깐이라도 보여주세요.
- [x] 06:04 여기서는~ 부터 63페이지로 가 주세요. 필요하면 오디오/비디오 분리. 
- [x] 07:10 없애지 그래? 아니라던지.... 말 연결이 이상해요
- [x] 07:33 위협적인.. 이라고 할 때 짤방 하나 넣어주세요.
- [x] 07:57 이 짤보다 뭔가 감사하는 짤이 좋아요. rawfootage / 자막과 짤방 모션템플릿 / 짤방 / 압도적감사 도 괜찮아요
- [x] 08:10 65페이지의 버그를 보시면.. 이라고 하면 Bug 소제목을 보여주세요
- [x] 08:13 화면이 불안하게 떨리네요
- [x] 08:24 그죠 자막 앞으로 넘겨주세요. 자막이 길어도 읽기 힘들지만 짧아도 읽기 힘들어요
- [x] 08:33 우리의 두뇌를 사용해서에 짤방 하나 넣어주세요
- [x] 09:25 쉐브론 chevron. 이런 상황에서는 종원님의 깐죽이 필요해요. 오~ 고급진 단어. 이런 효과 자막과 함께 간단한 사전 화면 캠쳐 같은 게 들어가도 좋겠네요
- [x] 12:31 으로
- [x] 13:07 남깁시다, 그런데 뭔가 해결을 못하고 뭉개는 거라서 시간을 확 잘라버립니다. 중요한 핵삼은 어카운트 입력하면 저 워닝 없어진다는 건데, 중간에 signing 관리 방식 바꾸는 건 덜어내 버리죠.
- [x] 13:39 entitlement
- [x] 14:32 동그라미 하나 고개 빼꼼 내밀고 있네요.
- [x] 문제 풀이할 때 보기를 미리 다 보여주고 있어야 이 화면을 보는 사람이 같이 생각을 하겠죠
- [x] 보기 나오는 부분의 border가 더 두꺼워 보여요. 갑갑해요
- [x] 15:38 맨 뒤에 왜 다시 시작하는 화면이 나오죠?
2차 피드백 완료

**3차 피드백**
- [x] 08:59 자막에서 '네' 는 감탄사니까 생략하거나 효과자막으로 분리해주세요.
- [x] 09:23 쉐브론 자막 너무 빨리 사라져서 뭔지 모르겠어요. 짤방이 두개가 나와서 더 눈에 안 들어오는 듯. 짤방은 지우고 효과자막을 키웁시다.

**Comment by manju-minji** [comment]
**1차 피드백**
- [] 00:02, 00:05, 00:36, 00:45, 01:35, 02:14, 02:27, 02:35, 02:38, 02:49, 02:59, 03:40, 03:48, 04:57, 05:13, 05:30, 05:35, 05:43, 05:51, 06:01, 06:56, 07:00, 07:12, 07:15, 07:20-07:21, 07:43, 08:15, 08:26, 08:29, 08:33, 08:36, 08:40, 08:53, 09:04, 10:16, 10:35, 10:42, 10:48, 10:58, 11:02, 11:23, 11:26, 11:33, 11:38, 11:50, 12:14, 12:19, 13:12, 13:25, 13:29, 14:08-14:11, 14:30, 14:58, 15:02, 15:09, 15:16, 15:24, 15:40, 16:08, 16:13, 16:26, 16:32 : 쩝 소리, 숨소리, 음소리, 어소리 등 흐름이 느려지는 부분, 소리가 튀는 부분 좀 더 컷팅해주세요.(이거 말고도 전체적으로 흐름이 느려지는 부분이 많은 것 같아요)
- [] 00:15 : 화면 나오고 자막 나오는 것 같은데 둘이 동시에 나오게 해주세요.
- [] 01:49 : 효과 자막(제일 왼쪽 것)을 화면 안쪽으로 조금 이동 시키는게 좋을 것 같아요.(조금 튀어나와 있어서)
- [] 03:18 - 03:22 : 검은 화면 나와요.
- [] 04:15 - 04:18 : 말이 없는 부분이라 이 부분은 자르고, 스크로를 좀 더 뒤에 하던가 앞에 하면 좋을 것 같아요.
- [] 04:36 - 04:38 : 화면이 아래로 움직여요.
- [] 04:45 - 04:48 : 검은 화면에 (연결 중) 이런식으로 하고 넘기던가 배속을 하던가 하는 식으로 빨리 넘기는 게 좋을 것 같아요.
- [] 05:37 : 네트워크 에 -> 네트워크에
- [] 06:28 - 06:29 : 화면 전환이 이상해요.
- [] 06:30 - 06:31 : breakpoint가 자막에 두번 나와요.
- [] 06:44 - 06:45 : 밑줄 선이 끝까지 안 그어져 있어요.(전반적으로 거의 글자보다 선이 짧은게 많은 것 같아요.)
- [] 07:43 : complie error 이게 너무 위에 있어요. 나중에 인덱스 넣을 때 문제 생길 수도 있어요~
- [] 09:10 - 09:38 : 예제 만드는 부분이 좀 지루해요. 이 부분을 2배속으로 재생하고 자막에 '예제 만드는 중' 뭐 이런식으로 위쪽에 넣어주면 좋을 듯 해요.
- [] 09:42 - 09:50 : 이 부분도 배속하고 'ㅇ배속 중' 이런식으로 자막 넣으면 좋을 듯.
- [] 11:44 - 11:47 : 이 부분도 배속하거나 좀 자르거나 하는 게 좋을 듯.
- [] 12:04 - 12:07 : 말 안하는 부분 잘라주세요(음성만)
- [] 13:14: 여기 보시면 어 이건 ~ 이 부분을 여기 보시면 / 어 이건 ~ 으로 잘라주세요. 어 이건~ 부분을 따음표 효과 자막으로 넣어도 좋을 듯.
- [] 13:46 - 13:51 : 자르던가, 배속처리하던가, 다른 음성 부분으로 옮기던가. 
- [] 14:37 - 14:39 : 방황하는 마우스 삭제해도 될 듯.
- [] 15:42 : 처음부터 15:44의 화면 위치대로 두는 게 좋을 듯.
- [] 15:57 : 문제 해석은 음성 그대로 따라갈 필요없고 좀 더 다듬는게 좋을 것 같아요.(ex. 실제 기기에서 코드를 실행시키기에 필요한 것은? 이런식으로)

처음이신데 수고 많으셨어요! 기대 이상으로 잘해서 놀람! 화이팅!
그리고 nas에 001파일 보시면 인트로, 아웃트로 영상 언제 넣으면 되는지 볼 수 있으니까 그거 확인하시고 넣으시면 될듯요~!

**Comment by lingostar** [comment]
@korECM 서체가 민지씨 작업이랑 달라요.

**Comment by korECM** [comment]
그 "" 사이에 있는 폰트 말하시는거면 수정 중이에요!

**Comment by lingostar** [comment]
@korECM 아뇨. 일반적인 바 자막이 서체가 달라요.

**Comment by korECM** [comment]
폰트는 수정했고 기존 
**14:37 - 14:39 : 방황하는 마우스 삭제해도 될 듯.**
부분은 배속하거나 중간에 잘라버리면 수강자가 어디서 저 오류를 확인하는지 헷갈려할 것 같아서 남겨놨는데 고려해서 한번만 더 봐주세욥

**Comment by korECM** [comment]
@lingostar  2차 피드백은 저 벨소리 하나만 삭제하면 될까요?

**Comment by lingostar** [comment]
@korECM 편집 반영한 걸로 다시 볼께요.

**Comment by korECM** [comment]
@lingostar 아 2차 피드백 주신 이후로 아직 수정된 부분은 없어요..! 저 부분 바로 수정해서 올릴까요?

**Comment by lingostar** [comment]
오디오 효과 넣었죠?  빼 주세요

**Comment by korECM** [comment]
@lingostar 
프로비저닝 아이콘은 찾았는데 Certificate 아이콘은 못찾겠는데 혹시 어느 아이콘인지 알 수 있을까요?

**Comment by lingostar** [comment]
@korECM https://i1.wp.com/macmule.com/wp-content/uploads/2015/09/Icon_CertificateStandard.png?resize=400%2C326&ssl=1

**Comment by korECM** [comment]
@lingostar 제가 저 아이콘 까먹구 반영을 못했는데 다음 피드백 때 올릴게요! 2차 피드백 반영버전 올렸어요!

**Comment by lingostar** [comment]
@korECM 3차 피드백 줬어요. 이제 인덱스 넣어서 완성하면 되겠네요.

**Comment by lingostar** [comment]
@korECM 수고 했어요. 마지막 업데이트 된 파이널 컷 파일을 올려주세요.
