### ISSUE TITLE
소개 페이지 정리

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#51]
- [x] 소개페이지의 경계선 스크래치 2 부분 없애기
- [ ] 커리큘럼 소개가 팀 소개 전에 와야 할 듯
- [ ] Lecturers 메뉴를 없애고 팀을 만들까 합니다.
     가능한 팀은 아래와 같고, 각 팀을 어떻게 시각적으로 표시할지와 내부에 담당자를 어떻게 표시할지를 제안 주세요.
    - Coding 교육 ( 김태선 )
    - Makers 교육 ( 이재훈 )
    - UX Design 교육 ( 남장혁, 김규원 )
    - App Development 교육 ( 이재훈, 박종영, 고준일, 강희종 )
    - 커리큘럼 지원 ( 김광호 )

- [x] 고객사 문구를 협력사 로 바꿉시다.

**Comment by PACMAN-X** [comment]
수정 사항

1. 커리큘럼과 관련된 내용도 추가하기

2. 교려대, 서울여대, 숙명여대 Delete

3. ADE, APLS 소개
