### ISSUE TITLE
하이파이버 인터뷰 - 이채원

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#60]
한양대 컴공과.  수업들은 후 휴학?하고 노예생활 시작.

엑서시즘이라는 알고리즘 문제의 난이도 정리, 
스위프트 퍼즐 북 맥용 앱 제작. (미출시)

지금은 카카오 네비? 근무 중.

**Comment by cl3499** [comment]
연락처 알려주시면 연락 취하겠습니다! :)

**Comment by lingostar** [comment]
업무기간 : 16년 12월 ~ 17년 7월, 314시간
업무내용 : 스위프트 알고리즘 퍼즐 정리, PuzzleBook Mac용 앱 제작
