### ISSUE TITLE
009_Unit1_8_InterfaceBuilder Basic

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#61]
**1차 피드백**

- [x] 00:32 '좋네요' 는 따로 자막을 분리해 주세요. 효과자막으로 넣어도 좋을 듯
- [x] 00:32~00:51 이 즈음에 소음이 깔리는데, 원본이 그런가요? 팬 도는 소리인가? 
--> 중간중간에 계속 잡음이 나왔다 사라지는데, 커트별로 달라지는 걸 보면 팬 소리가 아닐 수도 있어 보여요.
- [x] 01:14, 01:17 효과자막이 너무 큰 거 같은데 확인해 주세요.
- [x] 03:00 '져 화면' -> 저 화면 
- [x] 02:27 부쳤습니다 -> 붙였습니다 예요. attaching 하는 거거든요
- [x] 03:17 여기는 효과자막이 작게 나오죠? 효과자막 크기를 확인해 주세요.
- [x] 03:27 이상한 자막이 나와요
- [x] 04:39 짤방 회전 시키지 말고 넣읍시다.
- [x] 05:56 어떤 블로그인지 모르겠는데, 좌상단이 0,0 이라는 건 그냥 드로잉을 해도 금방하지 않을까요?
- [x] 06:00 지금 계속 화면 오른쪽의 인스펙터 이야기가 나오는데, 앞 레이아웃 가이드 때 확대한 것처럼 이 것도 오른쪽 귀퉁이를 확대해서 화면에 올려주면 좋을 듯 해요.
- [x] 06:25, 06:27 짤방이 확 와 닿지가 않아요.
- [x] 07:21 두셔야
- [x] 07:00 이 부분은, 이번 Xcode 11의 UI를 보여줄 필요가 있는데, 어떻게 보여주는 게 좋을까요? 이건 중간에 쌩뚱맞게 들어가도 괜찮을 듯. 
- [x] 07:43 이런 정보성 그래픽은 많을 수록 좋은데, 컨트롤 키를 기호만 표시하지 말고 키보드에 있는 모양 그대로 그래픽을 넣어주세요.
- [x] 07:52 자막에 이상한 글자
- [x] 08:07 전기 콘텐트 사진 짤방으로 넣어주세요.
- [x] 08:23 이럴 때 재미있는 짤방이 들어갈 수 있는 타이밍인데요
- [x] 09:13 자막을 빨간색으로 바꾼건 좋은데, 퀄리티가 떨어져요. 손 봐 주세요.
- [x] 09:41 노란색 배경에 빨간색 글자... 어디서 많이 본 컬러 스킴 아닌가요? ㅋㅋ
- [x] 10:06 버튼입니다. 버튼 에서 내가 이렇게 강조하는 단어는 효과자막으로 넣어주세요.
- [x] 10:53 이상한 자막
- [x] 11:30 구성분석으로 하는데요, 라는 자막이 나올 때 화면은 책을 보여줍시다.
- [x] 11:50 슬라이더를
- [x] 11:52 지금 자막과 다음 자막에 글이 섞여있어요
- [x] 11:00 ~ 12:00 그래픽 하나가 있으면 좋겠는데요, 함수가 있고, 버튼이 있고 슬라이더나 스위치가 있는데, 버튼으로 함수를 실행시키고, 똑같은 함수를 슬라이더 이동이나 스위치 온 오프로 실행하는 그래픽.
- [x] 14:08 책에서 예를 드는 건.. 이라고 하면 책 화면을 보여주세요. 15:00 까지 책을 배경으로 해야겠네. 밑줄도 잘 그어주고요. 
- [x] 15:15 나올까
- [x] 15:00 그리고 이 부분도 책의 내용을 따라가고 있는 거 같은데?! "이거 한 번 직접 해 보세요"라는 말은 책에서 제기한 화두를 학습자에게 직접 시키는 거거든요.
- [x] 15:31 이상한 자막
- [x] 15:50 이건 너무 과한 짤. 차라리 웃긴쪽으로 가는 게 좋을 듯. "스토리보드 쓰고 복 받으세요" 뭐 이런 느낌?!
- [x] 16:03 되네요
- [x] 16:19 이 부분도 책을 봐야 This App Rocks 라는 구문을 확인했을 꺼예요. 책 화면을 띄우세요.
- [x] 16:57 자막 이상
- [x] 18:00 짤방 요청

**2차 피드백**

- [x] 00:19 내가 말로 어~~~~엄청 중요하다고 했는데, 자막에 아무런 효과가 없으면 내가 무안해 짐. ㅋ 엄청을 효과자막으로 빼 주세요.
- [x] ~1:00 IBBasic 이라는 프로젝트를 만들고,말도 IBBasic 이라고 하는데, 자막만 IBBasics 예요. 2군데.
- [x] 4분 경에서부터 나오는 확대 이미지 너무 좋은데요, 확대된 이미지라는 걸 좀 느낄 수 있으면 좋겠어요. 배경을 흰색 아웃라인으로 준다던지... 파컷에서 쉽게 할 수 있는 방향으로 구분을 해 주세요.
- [x] 06:57 이건 완전 잘못된 거. 반드시 수정해야 해요. 아래 댓글에 사진 넣어놨어요.
- [x] 07:34 '어떤 버튼을 수정하고 싶을 때'라는 자막은 없어져야 해요.
- 08:25 펭수 적절했어요 ㅋ
- [x] 10:56 뗐을때
- [x] 11:46 애니메이션을 통해 설명하는 시도는 엄청 좋은데요, 오른쪽이 완전 함수 모양이었으면 좋겠어요. 오른쪽에 프로그레스 바가 있으니 더 헷깔려요. 그리고 설명 애니메이션이라는 영역 구분을 좀 해 주세요. 배경의 책에 뭍혀버려요,.
- [x] 15:49 짤방이 한 번에 이해하기 어렵고 인상깊지도 않아요. 이건 뺍시당
- [x] 16:41 이 부분에는 적당할 짤방이 있으면 좋을 것 같은데, 뭔가 이미 알고 있는데, 그래 속아줄께 그런 느낌. 아이가 어른에게 속아주는 그런 느낌?!
- [x] 18:15 직진, 직구, 돌직구. 뭐 이런 느낌의 짤방 있으면 좋을 듯.
- [x] 18:19 다 맞췄습니다.

**3차 피드백**
- [x] 03:31 이상한 자막이 나와요
- [x] 06:57 시간 조금 더 길게 해 주세요.
- [x] 나조차도, "이건 그냥 날 코드로 만들어야 돼" 싶은
- [x] 아웃트로 나오는 타이밍을 조금만 더 앞당겨주세요. 내가 킵 고잉~ 이라고 말 하기 전부터 음악은 이미 나오기 시작하도록.

- [x] 인덱스 컬러 맞추기

**Comment by lingostar** [comment]
@korECM 1차 피드백 완료. 맞춤법이나 띄어쓰기는 일일히 기록하지 않았어요.

**Comment by korECM** [comment]
@lingostar 반영한 영상 올려두었습니다!

**Comment by lingostar** [comment]
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/871180/69004010-3be2b100-094f-11ea-96ca-2bd3516179fe.png">
Xcode 11 에서는 이 메뉴예요,

**Comment by lingostar** [comment]
@korECM 2차 피드백 줬어요. 인트로와 아웃트로도 넣어주세요

**Comment by lingostar** [comment]
@korECM 3차 피드백 줬어요. 이거 작업하고 나면 바로 인덱스 넣고 완성합시다.

**Comment by lingostar** [comment]
@korECM 슬랙으로 준 서체 문제만 해결해서 다시 파이널 컷 라이브러리만 올려주세요.

수고 많았어요
