### ISSUE TITLE
010_Unit1_Guided Project - Light[gif]

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#63]
**1차 피드백**

전반적으로 호흡을 조금 더 다듬어 주세요. 조금 반복되어 의미 없는 말들이 있어요. 다음 리뷰때는 정확히 지점을 알려줄께요.
바꼈어요 -> 맞춤법이 맞는지 확인 해 봅시다. 
-> 저거 맞춤법 틀린거래요...하핳

- [x] 01:36 오브젝트 라이브러리의 위치가 바뀌어서 헤매는 사람이 있을꺼예요. 책의 버튼 위티를 보여주는 걸 조금 줄이고 커서가 윈도우 툴 바의 오브젝트 라이브러리 버튼으로 이동하는 것 부터 보여줍시다.
- [x] 02:00 책 찾아보는 검은 화면이 조금 길어요. 갑갑하지 않을 정도로만. 책 뒤적이는 장면을 조금 더 길게 넣어도 될 듯.
-> 화면 왔다갔다가 반복되서 오히려 정신없어 보일까봐 일단 검은 화면으로 편집했는데! 책 화면으로 일단 수정할께요!!
- [x] 06:03 이런 실수는 사용자가 같이 볼 필요가 없는 실수인 듯요
- [x] 06:50 이 부분의 실수는... 사용자들이 흔히 하게되는 실수겠죠? 자르려다가 살립니다.
- [x] 08:39까지만 남기고 뒷 부분 자릅시다. 08:55 까지. 여기서 중요한 건 모르는 값이 나오면 이렇게 파고 들어와서 찾아봐라는 거니까, 그걸 잘 전달하는 게 중요해요. 필요하면 효과자막으로 거들어 주세요.
- [x] 11:17 책 화면에서 선택이 변경되었는데, 어떤 내용이 변경되었는지 보이지 않으니 갑갑해요.
-> 저 변경 된 화면을 보시면서 설명을 하시는 중이 아니고 네번째단계~라는 말 하신뒤에 잠시 말 안하시는동안 바뀐거라서 저 변경 된 부분을 굳이 보여 줄 필요가 없다고 생각했어요. 저 화면이 설명에 사용되지 않는데 화면을 짤라서 넣는게 학생들에게 혼란을 줄 거 같기도 하고...(사실 짤라서 넣을 위치도 애매하기도 하고)그래서 일단 변경되는 부분을 아에 짜를게요!

**2차 피드백**
- [x] 07:25 스앵님, 지난 시간에 그거 했답니다. (009에서 했더라구요 ㅋ)
-> 그러면 뒤에 문서 읽는 부분도 다 짜르나요???
-> 아뇨, 자르진 말고 그냥 구박만 해 주세요

그리고 원래 대본에는 인덱스상 summary라는 부분으로 113페이지가 들어가는데, 영상에 113페이지가 없어서 그냥 책장 화면으로 대체 해놓은 상태라서 아웃트로랑 구분이 딱히 되지 않아요. 근데 인덱스에 summary라고 넣으면 혼란을 줄 거 같아서 그 부분을 인덱스에서 뺄까 싶은데 어떠세용??

-> 네, 빼 주세요. 

끝

**Comment by lingostar** [comment]
@manju-minji 1차 피드백 마쳤어요

**Comment by manju-minji** [comment]
업로드 했습니다!

**Comment by lingostar** [comment]
@manju-minji 2차 피드백도 마쳤어요. 이번 영상은 호흡도 괜찮아요. 추가적으로 손 볼 부분 저 문제 하나만 해결하고 바로 인덱스 붙여서 올려주세요.

**Comment by lingostar** [comment]
@manju-minji 답 줬어요~

**Comment by manju-minji** [comment]
업로드했습니다!

**Comment by lingostar** [comment]
@manju-minji 백업해 주세요
