### ISSUE TITLE
010 퍼즐세상

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#70]
**Final 피드백**

제가 AppDev 편집본을 많이 봐서 그 호흡에 익숙해져서 그런지
전반적인 호흡이 좀 느린 감이 있어요. @aawlgus96 님이 보기엔 예전 영상들에 비해 어떤가요?

- [x] 00:14 1프레임 손 보이는 거 없애주세요.
- [x] 01:30 '먼저 컬럼' 말하는 부분 덜어내 주세요
- [x] 04:40 두번째 6,2에다가 블럭 놓는 건 2배속을 쓸까요? 
- [x] 05:05 오른쪽 오른쪽 이라고 말하는 게 튀어요.
- [x] 아이패드 화면캡처와 카메라 촬영분의 사용 원칙은, 다음과 같아요. - 글자를 잘 보여줘야 하는 곳에서는 아이패드 화면 캡처를 씁니다. - 명령어 자동입력등 동작을 보여줘야 하는 곳에서는 카메라 촬영분을 씁니다. - 아이패드 화면 캡처만 너무 오래 나와서 지겨울 때 분위기 환기를 위해 카메라 촬영분을 넣어주기도 합니다. 지금은 글자가 흐린 카메라 촬영분이 너무 오래 나옵니다.
- [x] 07:50 @aawlgus96 예전에 혹시 본문에 줄 긋기 한 적 있지 않나요? 어디를 읽고 있는지 표시를 해 주면 좋을 것 같네요.
- [x] 10:35 효과자막으로 "복사하지 않고 함수를 정의해도 돼요" 라고 넣어주세요.
- [x] 10:50 앱이 죽는거 계속 보여주는 거 의미 없으니 빠른 호흡으로 지나갑시다. 앱 죽으면 "으아앙" 짤방 같은 거 한 번 보여주고, "적당한 빠르기로 실행해 봅시다" 라고 말 한뒤, 적당한 빠르기로 실행하는 건 저 쪽으로 넘어가서 멘트 나오기 전까지의 실행은 2배속으로 보여주세요. 
- [x] 12:20 퍼즐 다 풀고 홈 화면으로 나오는 부분도 몇 초 덜어내 주세요. 
- [x] 12:30 "아름답게 포장 좋았어" 하는 느낌의 짤방 하나 넣어주세요.
- [x] 12:40 오디오 이상해졌어요. 속도가 미세하게 빨라진 것 같은 오디오 느낌이예요. 아래 보니 속도감 있게 편집하라는 게 나오는데, 커트점을 많이 넣어서 내가 말 중간 중간에 쉬는 부분을 걷어내는 게 속도감을 높이는 거지 말 빨리감기를 하는 건 아녀요.
- [x] 12:53 에요 -> 예요
- [x] 13:06 킵고잉이라는 멘트를 아이패드 화면에서 했다면 "스위프트 하이" 라는 말은 아웃트로에서 나오도록 해 주세요.

피드백 완료

**3차 피드백**

- [x] 0:14 “자 들어가볼까요?” 뒤에 1초정도 여유 주고 인트로 들어가주세요

- [x] 1:04 “코딩 시작” 후 넘어가는 장면에서 앞 영상을 조금 늘릴 수 있으면 0.5초정도 여유 주고 들어갑시다. 사운드가 약간 튀는 느낌

- [x] 2:47 “좋아요” 효과자막 배경 없애고 심플하게 가거나 6:33 “안메웠다” 폰트로 변경

- [x] 2:54 “네~!” 효과자막 그냥 단색 (노랑이나 주황 등)으로 해서 심플한 폰트로 가죠

- [x] 3:24 떨어지는 사운드 들어갈 때 효과자막으로 피융 이런거 추가하면 좋을 것 같아요

- [x] 3:30 “흠..” 효과자막도 배경 없애고 심플하게 가는 것 어때요?

- [x] 4:02 해요 뒤에 마침표 다른 자막과의 통일성을 위해 없앱시다 

- [x] 6:20 세번 할 때 나오는 효과음이 좀 어색하네요. 정답이라는 느낌 주는 심플한 효과음이면 좋겠는데 
https://www.youtube.com/watch?v=KDGq81bDclE 이런 것들도 참고해주세요 👍

- [x] 6:33 안메웠다 -> 안 메웠다

- [x] 6:54 어?! 효과자막으로 처리해주세요

- [x] 7:16 있을거 같아요 -> 있을 것 같아요

- [x] 7:24 짝짝짝ㄱㅈㅅ이런 효과자막은 영상 분위기랑 안 어울리는 것 같아요. 그냥 박수 이모티콘 👏👏이런거 쌓이게끔 하는 건 어때요?

- [x] 7:33 테두리 추가 + 그림자 반으로 줄입시당 

- [x] 7:59 놓친 -> 놓진

- [x] 10:52 허 이자막 너무 빨리 사라지는 것 같아요. 효과자막으로 넣고 조금만 길게 띄워주세요

- [x] 12:00~ 포탈 -> 포털로 용어 통일

- [x] 12:35 디버깅 효과자막을 위에 띄우고 바자막은 그대로 가는 거 어때요? 효과자막이 읽기에 너무 빨리 사라져서 ㅠㅠ

- [x] 12:45~ 아웃트로 좀더 속도감있게 편집하면 좋을 것 같아요. 

꼭 이거에 맞춰 다 하실 필욘 없어요! 본인 편집 스타일을 살리고 싶으시면 필요한 것들만 반영하셔도 됩니다 :)
궁금한 점 있으시면 코멘트나 슬랙 남겨주세요~

**Comment by aawlgus96** [comment]
- [ ] 바자막 표기 시 마침표 여부를 통일하는 게 좋을 것 같네요. 어디에는 마침표가 있고 어디에는 없어서. 기존에는 가독성을 위해 마침표 없이 적었었어요!

- [ ] 맞춤법/띄어쓰기 조금만 주의해서 타이핑 부탁드려요, 특히 코드 입력할 때에는 가급적 표기된 그대로 소/대문자 구분해서 적어주세요. 

- [ ] 목차가 있어 화면이 세 부분으로 분할되다 보니 조금만 뭔가를 추가해도 조잡해 보일 가능성이 커요. 색감이나 효과자막은 최대한 톤을 맞춰 주세요. 

- [ ] 효과자막, 목차 폰트를 좀더 가독성 있는 폰트로 바꿔주세요. 기존에는 배민 주아체, 배민 연성, 나눔스퀘어라운드 등 사용하였음

- [ ] 짤 사용 시 너무 대충 그린 듯한 일러스트는 빼주시고 가급적 실사 화면, 캡처화면 등 눈에 잘 띄는 것들로 구성해주세요. (유튜브 체널의 컨셉상)

- [ ] 전체적으로 머뭇거리거나 루즈해지는 부분 때문에 영상 길이가 많이 길어요. 최대한 전달하고자 하는 것들로만 구성하고 이외의 쓸모없는 부분은 과감히 잘라주세요.

- [ ] 바자막 끊는 단위 좀더 길어도 괜찮습니다! 너무 세세한 부분까지 나누지 말고 최대한 한번에 보일 수 있게 해주세요. 그러기에 너무 쉬어가면서 말하는 부분이 있다면 사이사이를 잘라주시면 됩니다

0:02 “세상 만들기” 등의 주제 효과자막은 기본 효과자막 폰트랑 동일하게 유지해주세요. 일정하게 쓰는 폰트가 정해져 있고 그위에 추가적인 기타 폰트 추가하는게 영상 일관성에 맞을것 같네요!
0:11 “괜찮아요” 따옴표 조금 뜬금없는 것 같기도
0:16 컷신 -> 컷씬 (원래 쓰던 표현대로)
0:26 결, 설명하면 됩니다 부분에서 잘못 말한 ‘결’ 오디오 컷해주세요!
0:36 World -> world (표기된 그대로)
1:05 컷 넘어가는 부분에서 화면 튀지 않게 목차 바로 나오게 해주세요
1:09 호퍼 이미지가 목차나 콘텐츠를 너무 가리지 않게 줄여주세요. 
1:21 옆칸 한칸만 -> 옆 칸 한 칸만
1:22 새타일 -> 새 타일
1:24 컷이 좀 튀는 것 같아요. 그리고 하나하나 지목할 때 (3,3)과 같은 글씨가 그림상에 잘 안보일 수 있으니 한번 더 덮어 표기하면 더 좋을듯요
1:46 Place -> place (표기된 그대로)
2:00 앞서 말한 핑크색 따옴표 효과. 옆에 목차 노랑/초록색이랑 우측 빨간색 동그라미랑 색조합이 중구난방인 느낌? 좀더 단일한 색감으로 통일할 수 있으면 좋을 것 같습니다
2:05~ 바로해도 될것 같아요 -> 바로 해도 될 것 같아요/ 한칸 두칸 -> 한 칸 두 칸
2:28 Turn right -> turn right() (표기된 그대로)
2:37~2:41 이런 부분들은 과감하게 잘라주세요
2:43~44 이런 부분들 바자막 튀지 않고 이어지게 해주세요 (다른 부분들도 마찬가지)
3:08 이렇게 콘텐츠에 나와 있는 부분들은 밑줄로 처리해도 괜찮습니당
3:15 메워야하는 -> 메워야 하는
3:18 그죠? or 그져? 효과자막으로 해도 좋을듯
3:26 효과자막이랑 같이 떨어지는 짤같은거 넣어도 좋을 것 같네요
3:31~3:48 이부분 머뭇거리는거 등 루즈해지는 부분 과감히 편집해주세요
3:57 효과자막 폰트 수정 부탁드려용
4:35 호퍼 앞자리에다가 로 수정
4:37 이런 머뭇거리는 부분 잘라내주세요
4:47 호퍼의 앞자리에 블럭 두 개를 놓아야 해요 로 수정
4:48~5:00 (효과자막으로 살리거나) 깔끔하게 편집해주세요
5:07 let하는 부분 잘라주세요. 음..어..이런 부분도 최대한 없애고 깔끔하게 자막 작성 부탁드려요
6:04 오른쪽으로 돌아요 -> 아! -> 돌기~ 이부분 자막이 조금 밀리는 것 같아요
6:25~6:27 컷해주세요
6:33 오타 수정 부탁드려요
6:43~44 공백 잘라내주세요
7:05 머뭇거리는 부분 편집
7:24 ‘이걸 for문으로 돌리겠습니다’ 나누지 말고 이렇게 한번에 보여주는게 가독성에 좋습니다
7:28 세번 효과자막 푠트수정+색상 좀더 눈에 띄게 부탁드려요
7:40~ ‘안 메웠다’ ‘실수 ㅜㅜ’ 등 효과자막으로 부탁드려요
7:42 짤 좀더 눈에 띄는 걸로 수정하는게 좋을 것 같아요. 실사 이미지나 화면 캡쳐같은걸로요!
7:47 짤이 화면을 너무 가리는 것 같아요. 차라리 화면을 블랙처리하고 짤만 띄운 뒤 삐익-하는 효과음을 넣거나 or 짤 작게 삽입하고 관련 효과음을 넣는 게 나을 듯요
7:48~7:53 아무 동작/사운드도 없이 진행되는 화면 잘라내주세요
7:57 짤 크기때문에 콘텐츠를 가리네요. 여기선 없애거나 작게 처리해주세요
8:07~8:20 에러난부분 더 짧게 편집+ 짤 조금만 없애거나 짤이 등장할 때 효과음을 넣어주세요
8:41 짝짝짝 이부분은 바자막 연결보다는 효과자막으로 처리하는게 나을 것 같습니다. 박수 이모티콘을 삽입해도 좋고요
8:51 포털을 직접 만든데요 -> 포털을 직접 만든대요 or 만드는데요
8:52~8:55 ‘오우 대단해요’ 효과자막으로 수정 후 공백 부분은 편집
9:49~9:53 사운드 없는 부분은 최대한 편집
10:58~11:03 쉬는 부분 편집
11:12 또해야죠 -> 또 해야죠 로 수정
11:31 right 반복되는 부분 자막 없애거나 효과자막 or 과정 시각화
12:08~13:45 에러난 부분 최대한 간단하게 편집. 너무 길어요
15:20~ 30초가량 검은 화면이 계속 나오는 것 편집해주세요

**Comment by aawlgus96** [comment]
- [ ] 목차 들어갈 때 우측에 초록 바탕색 보이는 것 없애주세요 + 목차 폰트 사이즈 좀더 키워도 될듯?

- [ ] 바자막 깜빡이는 것처럼 보이지 않게 웬만한 상황에서는 그냥 연속적으로 보이게 처리해주세요. 말 끝나자마자 사라지는것 말고 다음 자막 나올때 그대로 이어서 보일 수 있게…? 

1:04 ~ 05초 넘어가는 순간 화면 프레임 한두개정도 그냥 삭제해주세요. 같은 화면이 중앙에 나오고 오른쪽에 또 나오니 화면이 튀네요
3:17 그죠? 이미지 조금 부담스러운 것 같아요. 그냥 배민체같은 폰트 적용해서 효과자막으로만 처리해도 좋을 듯
3:23 호퍼 떨어질때 푸슝하는 효과음이나 효과자막이라도…? 
3:30 효과자막 넣을 때 뒷배경 도형 넣지 않고 그냥 글자 삽입하는 게 좀더 자연스러울듯 해요. 
3:47 ~ 3:51 “이걸 가지고 패턴을 만들어서 풀 수 있는데” 중간에 숨 고르는 부분들 그냥 편집해서 말 연결되게끔 해주세요
3:51 ~ 3:54 “저..” 이부분 편집
4:07 ~ 4:12 “근데 그게 현재 불가능하죠” ~ “우리는 그냥 놓읍시다” 이것도 바자막 튀지 않게 연속적으로 이어주세요. 자막 단위도 좀 길게 끊는 게 좋을 것 같아요. 
4:36 “점프를 시켜도 될 것 같아요” 로 수정
4:38 “안 놓아도” 로 수정
5:13 “아!” / “돌기 전에 스위치를 켤까?” => “(아!) 돌기 전에 스위치를 켤까?”
5:39 ~ “코드를” / “작성하기에 편할 것 같아요” => “코드를 작성하기에 편할 것 같아요”
6:29 이런 류의 효과자막이 들어갈 땐 효과음도 작게나마 넣어주면 좋을 것 같습니다
6:49 이미지 2/3 정도로만 정사각형으로 줄이면 어떨까요
7:36 여기 이미지도 마찬가지..? 뒤에 화면때문에 구성이 좀 이상해서 2/3정도로 축소하면 나을 것 같네요
7:45 효과자막 폰트 조금더 가독성 좋은것 없을까요! 뒤에 돼지꼬리나 도형은 없어도 될 것 같구 무튼 자막이랑 어울리는 방향으로~
7:58 “놓는데” 이런 사소한 부분까지는 바자막으로 안 넣으셔도 됩니다! 
9:35 ~ 9:38 그러고 나서 음… 이 부분 편집해주세요
10:13 “한 칸 앞으로 가면 포털로 들어갈 거고” 로 수정
10:57 이미지 사이즈 줄이거나 없애도 될 것 같아요
11:07 자막 조금만 더 길게 이어지게 해주세요. 너무 빨리 넘어가서 읽기 힘들 수도
11:09 짤이 조금 부담스러운데 김혜수 죽겠어요 짤이나 심슨같은 귀여운짤 사이즈 줄여서 넣으면 어떨까용
11:13 “이럴 땐 한번 앱을 날렸다가” 로 수정 (음..어.. 이런 것들 다 넣을 필요는 없어요!)
12:52 디버깅이라는 용어 나올 때 효과자막으로 “디버깅” 표시해주기
13:26 구독좋아요공유 이미지 사이즈 10%정도만 줄이기

**Comment by lingostar** [comment]
@newGarlic 효과자막은 재미요소 + 이해를 돕는 용도 입니다. 

예를 들어, 마인 크래프트 이야기가 나올 때, 관련 그래픽을 추가한다던지
뭔가 내가 말로 길게 설명하는 부분에서 그걸 그래픽으로 풀면 좋겠다 싶은 부분이 있으면, 
마늘이 직접 하지 않더라도 디자이너에게 요청해서 만들어 줄 수 있어요.

재미 요소는, 너무 과하지 않은 선에서 , 식상하지 않게 해 줘야 합니다.
뻔한 짤은 없으니만 못해서, 너무 1차원적인 짤 보다는 예외적인 거나, 한 두단계 생각을 함축한 짤이 빵 터지게 만들죠.재미있는 짤 만들기는 우리 함께 생각을 모아 봅시다.

**Comment by lingostar** [comment]
@newGarlic 아직은 기존의 편집본과 달라서 튀는 부분이 있어요.
변화한 부분이 개선이 되었다면 눈에 거슬리지 않지만
수준에 못 미치면 눈에 튀어 보여요.

**Comment by aawlgus96** [comment]
4차 피드백

3:24 피융 소리 반 정도 줄일 수 있을까요? 효과자막도 바자막이랑 안 겹치게 호퍼 옆에다가 배치하면 좋을 것 같아요
5:08 (아!) 이 부분은 너무 빨리 지나가길래 뒤에 바자막이랑 합치거나 생략하자는 뜻이었어요. 그냥 아! 라고 넣어주세요
6:40 짤 가운데로 배치 부탁드려요
7:34 효과자막 스타일(크기, 그림자, 테두리 등)은 영상 내 통일 부탁드려요! 여기에서는 테두리 라인이 없네요
12:36 여기서도 효과자막이랑 바자막이 겹치네요. 이렇게 강조되는 용어를 효과자막으로 넣을 경우 자잘한 설명 바자막은 생략해도 됩니다

**Comment by lingostar** [comment]
@newGarlic 피드백 줬습니다. 파이널이 될지는 모르겠네요.
