### ISSUE TITLE
018_Unit2_8_Displaying Data

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#79]
**1차 피드백 by.민지**

- [x] 00:08 인트로 아웃트로 부분 가이드북 참고하셔서 화면 사이즈 조정해주시고 배경 이미지 넣어주세요. 그리고 
 인트로, 아웃트로 영상 빠지셨네요.
- [x] 00:26 fade out/in 빠짐.
- [x] 02:17 아 실수 부분에 짤 하나 넣어주세요.
- [x] 02:53 스태틱 데이터는 영어로 표현해주시는 게 나을 듯.
- [x] 05:08 상황에 어울리는 짤 넣어주세요.
- [x] 06:02 아이패드 화면이 나타났다가 사라지네요.
- [x] 07:04, 07:08 화면 스크롤이 없네요.  

전체적으로 화면 스크롤 속도가 좀 빠른 것 같아서, 조금 느리게 해주시면 좋겠어요.
그리고 fade out/in 속도도 빠른 것 같은데 기준점으로부터 14프레임 앞, 뒤에 효과 넣으신 것 맞나요?
코딩할 때 맥 화면이랑 아이패드 화면 번갈아 보여줄 때는 화면 전환 효과 굳이 안 주셔도 돼요.

**2차 피드백 by.민지**
- [x] 저번 피드백에서도 말씀드렸는데, 인트로 부분 화면 사이즈 조정 배경 이미지 넣어주세요.
- [x] 00:22 글자 길이에 맞게 밑줄 그어주세요.
- [x] 01:32 다뤄볼 겁니다
- [x] 01:40 한 페이지를 말하는 겁니다.

**3차 피드백 by.민지**

- [x] 00:08 들어가 볼까요
- [x] 00:34, 00:39 선 길이 글자에 맞게
- [x] 01:12 몇 가지
- [x] 01:18 평소 때의 하루는
- [x] 01:20 그런 것들
- [x] 01:34 있는 것처럼
- [x] 01:40 고민해보자고요
- [x] 01:43 잡는 거죠
- [x] 02:05 있을 겁니다
- [x] 03:51 오타 있는 듯
- [x] 04:16 사진을 쓸 때는
- [x] 04:35 저도 하고 있죠?,  하는 거 보시고
- [x] 04:42 책에 있는 건
- [x] 05:15 그림 넣을 때
- [x] 05:29 만든 걸로 인식돼요
- [x] 05:32 만들 때도 마찬가지예요
- [x] 05:49 자막 타이밍 조절
- [x] 06:33 이해가 안 되나요
- [x] 06:35 자세히 배울 거예요
- [x] 06:39 만들 겁니다
- [x] 07:18 만들어 보는 걸로

다음번에  인덱스  넣어서 올려주세요!
 

**4차 피드백 by.민지**

- [x] 00:14, 00:34, 00:40, 01:51, 01:57   밑줄 글자 길이에 맞게
- [x] 00:18 slack으로
- [x] 00:48 뭐 일단 전에 끊어주시고, 뭐 일단은 뒷 자막에 이어주세요. 뒷자막과 이어질 때 중간에 숨 소리는 없애주시고(뭐 일단, 앱의 기획 ~ 으로 만들어 달라는 뜻)
- [x] 00:52 - 01:23 꽤 긴 시간 동안 책의 글씨와 자막이 겹쳐져 있어요. 위치 조정 바람.(06:51~ 도)
- [x] 03:15 확대화면 넣어주세요.
- [x] 03:36 화면 전환 속도 확인 바람
- [x] 03:58 책과 동일한 명칭
- [x] 04:22 , 말고 ~
- [x] 05:14 넣을 때
- [x] 05:16 Scale To Fill
- [x] 05:32 만들 때도 마찬가지예요
- [x] 05:49 자막 없어지는 타이밍 이상
- [x] 05:52 slack에서
- [x] 05:59 가이드북에서 설명한 확대 방식으로 수정 바람.
- [x] 06:02 필요 없고요
- [x] 06:26 다 붙여서 쓸거면 맨 앞 c 소문자, 그리고 여기도 확대 화면
- [x] 06:33 할 때 / 배울 거예요, 아마.
- [x] 06:35 예고한 대로
- [x] 06:39 만들 겁니다
- [x] 06:51 따라가는 거네요
- [x] 07:18 만들어 보는 걸로 끝내자고요

**5차 피드백 by.민지**

- [x] 00:18 사진 조금 키워주시고 사진 위쪽과 사진 아래쪽 자막과의 간격 비슷하게 맞춰주세요
- [x]  planning~, enter ~ 부분  인덱스 타이밍 가이드북 자주하는 실수 부분 참고 바람.
- [x] 00:39 글자가 줄에 묻히는 느낌이라 밑줄을 살짝 아래로
- [x] 01:25 static data 핑크색 박스
- [x] 01:33 이 부분에서는 설명에 해당하는 책의 텍스트가 아닌 예시를 보여주는 게 나을 듯. 
- [x] 02:05 검은 화면
- [x] 02:26, 02:31, 02:37, 02:41, 02:49 SwiftUI
- [x] 03:38 UILabel
- [x] 03:39 UILabel의 설명 ~ / 213페이지 음성과 자막 순서를 바꿔주세요.
- [x] 03:51 지난번에도 말한 부분인데, 필요한 만큼의 줄이 추가된다 아닌가요?
- [x] 05:05 꽃 자막
- [x] 05:44 확대 화면
- [x] 05:45, 05:50  글씨체 바꿔주세요.
- [x] 07:23 마무리 부분은 인덱스 안넣어도 돼요.

**6차 피드백 by.민지**

- [x] 00:18 slack으로 
- [x] 01:26 slack으로
- [x] 인덱스 등장 타이밍 조금 더 앞으로 당겨서 화면 조정될 때 인덱스도 같이 전환되게 해주세요.
- [x] 02:49 지난번 피드백 반영 안 됨.
- [x] 03:39 자막만 바꾸는게 아니라 음성도 같이 
- [x] 04:56 화면과 동일하게 star

**7차 피드백 by.Lingo**
현목님, 수고많네요. ㅎㅎ 이 티켓도 체크사항이 엄청나군요~! 😮
- [x] 00:53 ~ 01:07 동일한 내용의 설명이 두번 반복되지 않나요?
- [x] 04:21 이 짤은 뺍시다. ㅎ 웃기거나 도움이 되지 않아요
- [x] 04:34 와 04:37 을 아이콘 배치와 글자를 동일한 포맷으로 가져갑시다

**Comment by lingostar** [comment]
@manju-minji 1차 피드백 주세요

**Comment by choihyunmok** [comment]
4:21 나중에 설명을 드릴 거고요

**Comment by lingostar** [comment]
@choihyunmok @manju-minji 수고 많았어요~ 위 수정사항 반영한 뒤 백업합시다.
