### ISSUE TITLE
019_Unit2_9_Controls In Action

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#80]
**1차 피드백 by.민지**

- [x] 01:41 공간좀 -> 공간 좀
- [x] 02:02 자막이 지금 왼쪽으로 치우쳐져 있는데, 기본 자막에서 '이벤트로' 앞에 박스 자막 크기에 맞는 빈 공간을 만들어주시고(스페이스나 탭 이용) 거기에 박스 자막 넣어주세요.(15:34도 마찬가지)
- [x] 02:07, 06:19, 등등  이런 확대 화면 나올 때는 확대 화면이라는 걸 명확히 표시할 수 있는 걸 넣어주면 좋을 듯(테두리 박스 같은...?) 
- [x] 02:19 라는 앞에 부분 말에 ' ' 이런 거 넣어주면 좋을 듯!
- [x] 02:24 짤 넣은 의도는 알겠는데, 좀 더 직관적으로 한번에 이해 할 수 있는 짤이 좋을 듯.
- [x] 전체적으로 박스 글씨체 크기 몇이죠? 크기 80이 적당한데
- [x] 02:40 두개 박스 y축 위치 맞춰주세요.
- [x] 02:48, 14:35 끊기는 부분 없애기.
- [x] 03:09 Xcode 상에 sender 소문자이니까, 소문자로 자막 넣어주는 게 좋을 듯.
- [x] 05:50 자막 뒤에 글자가 보여서(게다가 자막 배경 색과 같은 흰색) 글자가 한눈에 안 들어와요. 조정 부탁드려요!
- [x] 06:28 상황에 어울리는 짤 넣으면 좋을 듯.
- [x] 06:50, 07:53  말 머뭇거리는 부분 커트.
- [x] 07:19 어디까지 가나보자 이런 느낌 짤 넣으면 좋을 듯.
- [x] 08:15 입력되었을 때입니다.
- [x] 08:53 이 강의를 듣는 사람들에게는 한 번에 이해하기 어려운 짤 일 듯.
- [x] 12:03 값을 바꿀 수 있겠죠.
- [x] 12:32 못 만들어요.
- [x] 12:43 거절, 별로 뭐 이런 느낌의 짤 넣으면 좋을 듯. 그리고 쓰고싶은 -> 쓰고 싶은
- [x] 12:56 적고나서 -> 적고 나서
- [x] 13:49 자막이 화면 밖으로 나가지 않도록 크기 조정 바람.  
- [x] 14:05 그것때문에 -> 그것 때문에
- [x] 14:30 끊는 걸
- [x] 14:32 나온 김에
- [x] 16:08 자막이 깨지는 것처럼 보이는데, 확인 부탁드려요.
- [x] 16:13 중요한 건
- [x] 16:57 애->에
- [x] 17:25 아니기 때문에
- [x] 18:38 어울리는 짤 넣어주세요.
- [x] 18:50 스와이프 같은 거를
- [x] 18:52 올라올 거잖아요.
- [x] 19:24 자막 이상
- [x] 22:00 기억해두셔야 돼요. 
- [x] 23:30, 23:35, 25:27 p->b 
- [x] 24:25 보일 거라는 거지
- [x] 24:30 안 나오는 거
- [x] 26:13 '알지?' '느낌 알지?' 뭐 이런 느낌의 짤이 나을 듯. 
- [x] 28:30 '문제에서'는 걷어내주세요.
- [x] 28:35 이런 건
- [x] 29:08 여백이 없도록 박스 크기 맞춰주세요.(다른 문제도 마찬가지) 
- [x] 29:39 아이패드 화면 뒤에 맥 화면이 나오네요. 
- [x] 29:51 안 가르쳐준 거, 그리고 깜박이 좀 키고 들어와 이런 느낌의 짤 넣어주세요.
 
 **2차 피드백 by.민지**

- [x] 00:29 설명중인 내용이 화면 너무 윗부분에 있어서 중간 쯤으로 위치 조정 바람.
- [x] 00:38  화면전환 효과 빠짐
- [ ] 01:47  1차 피드백의 02:07 부분 피드백과 동일 
- [ ] 02:06
- [x] 04:58 이런 게 잘 없죠, 잘 안 맞죠
- [x] 05:18, 05:19 Xcode 상에 sender 소문자이니까, 소문자로 자막 넣어주는 게 좋을 듯.
- [x] 05:43 안 나오거든요
- [x] 06:40 연결을 할 겁니다
- [x] 06:48 말 다듬어주세요.
- [x] 07:08, 08:04, 08:09, 08:25 오타
- [x] 07:50 액션과 함수를 연결하는 겁니다
- [x] 09:01 뒤에 화면을 보면 editing changed 이렇게 중간에 띄우네요. 중간에 띄워주세요.
- [x] 09:20 그 값을 쓸 거라서
- [x] 10:29 자막 잘못됨. 그리고 상황에 맞는 짤 넣어주세요.(당황 뭐 이런 느낌)
- [x] 10:45 이름 같은 거는
- [x] 12:37 이렇게 쓰고 싶은
- [x] 15:22 버튼을 누르면 에서 한번 끊어주세요.
- [x] 15:58 gesture에 강조 자막
- [x] 15:59  gesturerecognizer 강조
- [x] 16:04  수 있는에서 자막 끊고 제스처 인식 기구는 따옴표 자막
- [x] 16:21 사실 그럴 필요 없이 에서 끊기
- [x] 16:51  붙여 볼 건데요.
- [x] 18:29 숨겨놓은 기능 같은 건데
- [x] 18:32 기능이 있긴 해요
- [x] 18:50 이 는 빼는게 나을 듯.
- [x] 19:09 거의 안 바뀌고
- [x] 21:08 Inside
- [x] 21:39 만들어 붙인 겁니다
- [x] 21:43 동일한 거예요
- [x] 21:52 중요한 건
- [x] 25:52 안 좋아하거든요
- [x] 26:56 (아무것도 없는 걸로) 가 낫지 않을까요?
- [x] 27:20 안 없어지죠
- [x] 27:31 미리 두번 나옴
- [x] 28:31 후훗! 하는 느낌의 짤 넣어주세요
- [x] 29:40 다루는 건

**3차 피드백 by.민지**

- [x] 01:19 뷰에 View
- [x] 01:25,  01:46, 17:24 이런 확대 화면 나올 때는 확대 화면이라는 걸 명확히 표시할 수 있는 걸 넣어주면 좋을 듯(테두리 박스 같은...?) 
- [x] 05:25 확실히 알고 있어
- [x] 05:32 하나 있을 겁니다
- [x] 05:39 타이핑 안 하면
- [x] 06:36 추가를 하네요 에서 스페이스 한번 넘게 눌린 것 같아요.
- [x] 07:12 좀 어려울 거라고 보는데
- [x] 07:22 화면에 표시된 대로 중간에 한번 띄워줘요.
- [x] 07:38 연결되는 건
- [x] 07:49 액션 하고 말 끊기는 부분 잘라주기
- [x] 08:21 옵셔널 두번 나오는거 다듬기
- [x] 08:51 호출될 거고요
- [x] 09:15 라고 하는 함수를
- [x] 09:52 흐름상 있습니다가 나을 듯.
- [x] 10:04 내용이 어떤 내용이냐는 거죠.
- [x] 10:15 추천을 해준다는 거죠
- [x] 10:18 그리고 요런 거
- [x] 11:47 저게 어떤 건지 한번
- [x] 13:26 오타
- [x] 13:57 끊은 게 있는데
- [x] 15:29 자 앞에 빈칸들 없애주세요
- [x] 15:35 대응을 하고 있죠
- [x] 15:37 버튼 같은 거
- [x] 16:35 https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=116756  상황상 함께 할 이 맞는거 같죠?
- [x] 17:13 -  17:17 액션 함수
- [x] 17:28 오타
- [x] 18:21 실행된다든지
- [x] 18:39 자막 이상
- [x] 19:33 싶긴 한데
- [x] 20:23 로딩되고 나서 잘라주세요
- [x] 20:58 되는 거고
- [x] 20:59, 24:59 화면과 동일한 명칭으로 바꿔주세요.
- [x] 21:37 연결이라는 말 자를 수 있으면 잘라주세요.
- [x] 22:21 글자와 밑줄 길이 맞춰주세요.
- [x] 22:32 이런 것 때문에 여러분들이 비디오를 보는 거죠.
- [x] 23:20 만들어졌고
- [x] 23:28 연결이 된 거고
- [x] 23:30 연결이 된 겁니다
- [x] 29:06 안 읽어봐도
- [x] 29:44 안 가르쳐준 거, 물어보는 거

매 피드백에서 비슷한 이유로 지적되는 부분이 많은데 제가 피드백 과정에서 못 보고 넘어가는 부분이 있을 수도 있어요. 그리고 한 번만 다시 확인해주시면 쉽게 문제를 발견할 수 있는 부분들도 있고요. 제가 짚어준 부분만 수정하지 마시고 꼼꼼히 전체를 봐주시면서 부족한 부분이 뭔지, 더 수정할 건/추가할 건 없는지 확인해주시면 영상의 퀄리티가 더 좋아질 것 같아요~파이팅!

그리고 확대창 테두리를 어떻게 넣는 것이 더 좋을 지 상의해야 할 듯.

**4차 피드백 by.민지**
- [x] 00:09 끊김 없이 바로 인트로 영상 이어지게 해주세요
- [x] 00:24 맞물려 돌아가는지를
- [x] 01:34, 10:42  오타
- [x] 01:47, 17:23 테두리 같은 것 넣어주세요.
- [x] 05:16 찾을 겁니다
- [x] 05:19 sender라는 게
- [x] 07:34 '여기도'가 흐름상 더 자연스럽지 않을까요?
- [x] 08:44 작성하는 거예요
- [x] 08:56 텍스트 필드는 여러 가지
- [x] 10:35 텍스트 필드
텍스트 필드라는 단어가 나올 때 영어랑 한글이 번갈아가며 나오는데 소개할 때는 빼고는 한글로 통일해주는 게 나을 듯.(영상 뒷부분에서는 계속 한글이 나오네요)
- [x] 16:39 붙이는 게 아니라
- [x] 18:30 이미지 설명이 너무 순식간에 지나감. 말 끝나고 gap을 하나 넣은 뒤에 이미지 설명과 상황에 어울리는 자막 브금 깔아주면 좋을 듯.
- [x] 18:41 받는 거죠
- [ ] 20:39 오버워치에서 '목표를 포착했다' 이런 짤 넣는 거는 좀 별로이려나?
- [x] 22:59 만들 걸 그랬나
- [x] 24:08 - 24:10 자막 화면과 일치시켜 주세요.
- [x] 27:20 이러시면 곤란하지 이런 느낌의 짤 넣어주세요.
- [x] 28:25 칭찬에 신남 보다는 은근 슬쩍 잘난 척 이런 느낌이 상황에 더 어울릴 듯.

지금 피드백의 80% 이상을 차지하고 있는 게 오타, 띄어쓰기 등 맞춤법 관련이에요. 다음번 영상 제작하실 때는 자막 넣으실 때 맞춤법 검사기 돌려보고 넣으시면 좋겠어요.

그리고 다음 번 영상에서는 인덱스 넣어주세요~

**5차 피드백 by.민지**

- [ ] higher 시작 전 잡음 다 잘라주고 바로 시작하는 걸로.
- [ ] 인덱스 크기 화면에 맞춰주세요. 가이드북 보면 설명 있으니 참고 바람. 인덱스 크기 안맞아서 자세히 안 살펴봤어요.
- [ ] 00:19 자막들이 최대한 이어지게 해주세요. 차라리 길게 끊기는 부분은 괜찮은데 아주 잠깐 자막이 끊기면 화면이 깜박이는 듯하고 흐름이 끊기는 느낌 들어요. 
 
**6차 피드백 by Lingo**
- [x] 01:07 Main.storyboard
- [x] 01:17 어시스턴트 뷰가 아닌데 왜 어시스턴트 뷰라고 이야기 한거지? 오디와랑 화면 매칭이 정상이라면 어시스턴트라는 말 잘라주세요. 아, 나중에 어시스턴트 뷰를 여는구나. 앞쪽은 잘라주세요.
- [x] 2:46. 2:50 sender s 소문자
- [x] 08:16 . 08:20 바꼈을 때 -> 바뀌었을 때
- [x] 12:57 연결 경고 난 부분, 없애는 부분은 확대해 주세요.
- [x] 13:23 Playground

**Comment by korECM** [comment]
나스에 1차본 업로드 했습니당 인트로랑 아웃트로 배경 이미지가 저한테 없어서 일단 빼고 작업했고 이 부분은 다음 피드백 때 추가하겠습니다. 또한 각 챕터 사이에 장면 전환 또한 다음 피드백 때 추가하겠습니다!

**Comment by korECM** [comment]
01:47 1차 피드백의 02:07 부분 피드백과 동일
  02:06
이거 2개는 뭔지 모르겠어서 일단 빼고 한 영상 렌더링 해서 올릴게요!

**Comment by lingostar** [comment]
@korECM @manju-minji 피드백 줬어요. 이거 반영하고 바로 백업 들어갑시다

**Comment by lingostar** [comment]
@korECM 5차 피드백의 내용은 반영했나요?

**Comment by manju-minji** [comment]
@lingostar 저거 체크만 안됐고 반영 되어 있어요!!
