### ISSUE TITLE
[TJBot] 오디오 이슈 해결

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#88]
TJBot은 오디오-인을 위해 USB 마이크를, 오디오-아웃을 위해 블루투스 스피커 사용을 권장.
3.5pi 오디오 단자는 막아둔 상태.
오디오 출력을 위한 SW|HW 적인 해결 방법 필요

USB 스피커 중 동작을 잘 하는 것을 찾지 못함.

블루투스 스피커 구입. 마이크도 있는 것.
블루투스로 마이크/스피터가 모두 해결 가능하면 원가 절감 가능

**Comment by DevKang** [comment]
- 블루투스 스피커 + 마이크 모델의 경우 라즈베리파이 내장 블루투스 드라이버 이슈로 정상 이용 불가
- 블루투스 스피커 + USB 마이크로 사용해야 함

[추가 이슈 및 해결]
- 블루투스 스피커 이용 시 기본 장치인 Alsa 대신 PulseAudio 사용이 더 보편적이고 안정적임
- TJBot 에서 기본 플레이 장치로 Alsa의 디폴트 장비로 세팅 되어 있음
- tjbot-daemon 에서 config.js 에 다음 내용을 추가하면 장비를 PulseAudio 로 변경 가능
```js
exports.tjConfig = {
    // 기존 세팅
    speak: {
        speakerDeviceId: "pulse"
    }
}
```
