### ISSUE TITLE
[웹사이트] 학생 결과물 찾아서 추가

### ISSUE THREAD

**Issue by lingostar** [ProjectInTheClass/CodersHighOffice#90]
아래 앱 스토어 링크 넣어주세요.

- [x] 독서노트 - 중앙대 첫 강의때 신길용이 만든 것
- [x] 영어라디오 - 권병수가 만든 것
- [x] 암기하개 - 중국애들이 지네꺼라고 올린 거
- [x] 알바고 - 러시아 애가 지네꺼라고 올린거
- [ ] 2018 동국대 원샷톡 https://codershigh.github.io/WebSite/edureports/2018_dgu_winter.html 은 학생들에게 연락 가능한지 확인

**Comment by PACMAN-X** [comment]
- 독서노트 : 앱스토어에서는 찾을 수 없음
- 암기하개 : 앱스토어에서는 찾을 수 없음
- 알바고 : 앱스토어에서는 찾을 수 없음
