### ISSUE TITLE
[F]수료생 입력창

### ISSUE THREAD

**Issue by PACMAN-X** [ProjectInTheClass/CodersHighOffice#91]
- [ ]  수강생 입력창
    - [ ]  개인정보
        - [ ]  이름
        - [ ]  App 이름
        - [ ]  팀원
        - [ ]  githubID
    - [ ]  URL
        - [ ]  프로젝트 웹사이트 url
        - [ ]  github 웹사이트 url
        - [ ]  appstore 웹사이트 url
        - [ ]  발표 동영상 url
    - [ ]  스크린샷
        - [ ]  앱스크린샷
        - [ ]  github 참여도 스크린샷([https://github.com/users/pacman-x/contributions?to=2019-12-31](https://github.com/users/pacman-x/contributions?to=2019-12-31))
        - [ ]  만든 이슈 스크린샷
        - [ ]  해결한 이슈 스크린샷

**Comment by PACMAN-X** [comment]
코더스하이 업무 폴더 - 수료증 프로토타입 참고

**Comment by lingostar** [comment]
코더스하이 학생관리 시스템의 일부
