### ISSUE TITLE
[2-1] iOS DD 페이지 구조화

### ISSUE THREAD

**Issue by PACMAN-X** [ProjectInTheClass/CodersHighOffice#99]
- [ ]  iOS DD 페이지
- [ ]  iOS DD 레이아웃 구성 확정 후 디자인 요청( to 민기 )

**Comment by lingostar** [comment]
초안 문구를 작성해 봅시다. 

이 과정을 뭐라고 소개할 건지에 대해 지금 NAS 에 올라가 있는 커리큘럼 파일을 참고해 주세요.
